local T = BPlus.test

T.test('Duke: holding 2 Kings -> X2 * X2 (vanilla: X1.5 * X1.5)', function()
    T.start_run({ jokers = { 'bplus_baron_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 * 2 * 2)
end)

T.test('Duke: holding no Kings -> no effect', function()
    T.start_run({ jokers = { 'bplus_baron_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'QS', 'QH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1)
end)

T.test('Duke: vanilla forced to "+" matches (vanilla 1 * 1.5 * 1.5, "+" 1 * 2 * 2 mult)', function()
    T.start_run({ jokers = { 'baron' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '2C', '9C', '6D' })
    T.force_behavior('baron', 'plus')
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 * 2 * 2)
end)

T.test('Duke: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'baron' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 * 1.5 * 1.5)
end)

T.test('Duke JokerDisplay: "+" shows the "+" numbers; vanilla forced to "+" shows them too; "+" forced to base shows vanilla numbers', function()
    T.start_run({ ante = 4, jokers = { 'bplus_baron_plus', 'baron' } })
    T.select_blind()
    T.set_hand({ 'KS','KH','2D','3C','5H' })
    local d = T.joker_display('bplus_baron_plus')
    T.eq(d.text, 'X' .. (2 * 2))
    T.eq(T.joker_display('baron').text, 'X' .. (1.5 * 1.5))
    T.force_behavior('baron', 'plus')
    T.eq(T.joker_display('baron').text, 'X' .. (2 * 2))
    T.force_behavior('bplus_baron_plus', 'base')
    T.eq(T.joker_display('bplus_baron_plus').text, 'X' .. (1.5 * 1.5))
end)
