local T = BPlus.test

T.test('War Banner: 3 discards left -> +60 * 3 Chips', function()
    T.start_run({ jokers = { 'bplus_banner_plus' }, ante = 3, discards = 3 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 60 * 3)
    T.eq(r.mult, 1)
end)

T.test('War Banner: 0 discards left -> no effect', function()
    T.start_run({ jokers = { 'bplus_banner_plus' }, ante = 3, discards = 0 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11)
    T.eq(r.mult, 1)
end)

T.test('War Banner: vanilla forced to "+" matches (vanilla 1, "+" 1 mult)', function()
    T.start_run({ jokers = { 'banner' }, ante = 3, discards = 3 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    T.force_behavior('banner', 'plus')
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 60 * 3)
    T.eq(r.mult, 1)
end)

T.test('War Banner: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'banner' }, ante = 3, discards = 3 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 30 * 3)
    T.eq(r.mult, 1)
end)
