local T = BPlus.test

T.test('Duke: holding 2 Kings -> X2 * X2 (vanilla: X1.5 * X1.5)', function()
    T.start_run({ jokers = { 'bplus_baron_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 * 2 * 2)
end)

T.test('Duke: holding no Kings -> no effect', function()
    T.start_run({ jokers = { 'bplus_baron_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'QS', 'QH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1)
end)

T.test('Duke: vanilla forced to "+" matches (vanilla 1 * 1.5 * 1.5, "+" 1 * 2 * 2 mult)', function()
    T.start_run({ jokers = { 'baron' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '2C', '9C', '6D' })
    T.force_behavior('baron', 'plus')
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 * 2 * 2)
end)

T.test('Duke: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'baron' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 * 1.5 * 1.5)
end)
