local T = BPlus.test

-- Hive Mind copies the UPGRADED ability of the leftmost joker (D23). Every lineup below is { target, others... };
-- the target goes first, Hive Mind goes last.
local COPIER = 'bplus_brainstorm_plus'
local function lineup(parts)
    local out = {}
    for _, p in ipairs(parts) do out[#out + 1] = p end
    out[#out + 1] = COPIER
    return out
end
local function run(parts, extra)
    local s = { jokers = lineup(parts), ante = 3 }
    for k, v in pairs(extra or {}) do s[k] = v end
    T.start_run(s)
    T.select_blind()
end
local function pair2()
    T.set_hand({ '2S', '2H', '7C', '9D', '3D' })
    return T.play({ '2S', '2H' })
end
local function compat()
    T.wait_frames(4)
    return T.joker(COPIER).ability.blueprint_compat
end
local function near(a, e, what) T.near(a, e, 1e-6, what) end

-- B1 Jolly: +8 Mult per Pair, "+" +20
T.test('Hive Mind: copies the "+" ability of vanilla Jolly Joker (+20, not +8)', function()
    run({ 'jolly' })
    T.eq(compat(), 'compatible')
    -- Pair of 2s: 10 + 2 + 2 chips; Mult 2 + own +8 + copy +20
    local r = pair2()
    T.eq(r.chips, 10 + 2 + 2)
    T.eq(r.mult, 2 + 8 + 20)
end)
T.test('Hive Mind: copies Merry Joker as it is', function()
    run({ 'bplus_jolly_plus' })
    T.eq(pair2().mult, 2 + 20 + 20)
end)

-- B2 Faceless: $5 for 3 faces discarded, "+" $6
T.test('Hive Mind: copies the "+" ability of vanilla Faceless Joker (copy $6 + own $5)', function()
    run({ 'faceless' }, { dollars = 0 })
    T.set_hand({ 'KS', 'QH', 'JD', '2C', '3C', '4C', '5C', '6C' })
    T.discard({ 'KS', 'QH', 'JD' })
    T.eq(G.GAME.dollars, 6 + 5)
end)
T.test('Hive Mind: copies Undercover Joker as it is', function()
    run({ 'bplus_faceless_plus' }, { dollars = 0 })
    T.set_hand({ 'KS', 'QH', 'JD', '2C', '3C', '4C', '5C', '6C' })
    T.discard({ 'KS', 'QH', 'JD' })
    T.eq(G.GAME.dollars, 6 + 6)
end)

-- B3 Ancient: X1.5 per card of the Ur-Joker suit, vanilla X1.5 per card of the Ancient suit
T.test('Hive Mind: copies the "+" ability of vanilla Ancient Joker (Ur-Joker suit)', function()
    run({ 'ancient' })
    G.GAME.current_round.bplus_ur_card.suit = 'Hearts'
    G.GAME.current_round.ancient_card.suit = 'Spades'
    T.set_hand({ 'KH', '2C', '3C', '5C', '7D' })
    -- the copy scores X1.5 for the Heart; the vanilla Ancient (Spades) does nothing
    T.eq(T.play({ 'KH' }).mult, 1 * 1.5)
end)
T.test('Hive Mind: copies Ur-Joker as it is', function()
    run({ 'bplus_ancient_plus' })
    G.GAME.current_round.bplus_ur_card.suit = 'Hearts'
    T.set_hand({ 'KH', '2C', '3C', '5C', '7D' })
    T.eq(T.play({ 'KH' }).mult, 1 * 1.5 * 1.5)
end)

-- B4 Scholar: Aces +20 Chips +4 Mult, "+" +40 / +10
T.test('Hive Mind: copies the "+" ability of vanilla Scholar (Professor numbers)', function()
    run({ 'scholar' })
    T.set_hand({ 'AS', 'AH', '9C', '6D', '3H' })
    local r = T.play({ 'AS', 'AH' })
    T.eq(r.chips, 10 + 11 + 11 + (20 + 20) + (40 + 40))
    T.eq(r.mult, 2 + (4 + 4) + (10 + 10))
end)
T.test('Hive Mind: copies Professor as it is', function()
    run({ 'bplus_scholar_plus' })
    T.set_hand({ 'AS', 'AH', '9C', '6D', '3H' })
    local r = T.play({ 'AS', 'AH' })
    T.eq(r.chips, 10 + 11 + 11 + (40 + 40) + (40 + 40))
    T.eq(r.mult, 2 + (10 + 10) + (10 + 10))
end)

-- B5 Constellation (growing): the copy uses the stored value and never grows it
T.test('Hive Mind: copies vanilla Constellation with its stored value and does not grow it', function()
    run({ 'constellation' }, { consumables = { 'venus', 'earth', 'mars' }, consumable_slots = 3 })
    T.use('venus'); T.use('earth')
    -- vanilla Constellation gained 0.1 per Planet: X1.2. The copy gained nothing.
    near(T.joker('constellation').ability.x_mult, 1 + 0.1 * 2)
    T.set_hand({ '2S', '2H', '7C', '9D', '3D' })
    near(T.play({ '2S', '2H' }).mult, 2 * (1 + 0.1 * 2) * (1 + 0.1 * 2))
    T.use('mars')
    near(T.joker('constellation').ability.x_mult, 1 + 0.1 * 3, 'one more Planet: only the original grows')
end)
T.test('Hive Mind: copies Galaxy with its stored value and does not grow it', function()
    run({ 'bplus_constellation_plus' }, { consumables = { 'venus', 'earth', 'mars' }, consumable_slots = 3 })
    T.use('venus'); T.use('earth')
    near(T.joker('bplus_constellation_plus').ability.extra.Xmult, 1 + 0.2 * 2)
    T.set_hand({ '2S', '2H', '7C', '9D', '3D' })
    near(T.play({ '2S', '2H' }).mult, 2 * (1 + 0.2 * 2) * (1 + 0.2 * 2))
    T.use('mars')
    near(T.joker('bplus_constellation_plus').ability.extra.Xmult, 1 + 0.2 * 3)
end)

-- B6 Popcorn / Ice Cream: carpenter_compat = false, so the regular ability is copied. Abstract: compatible.
T.test('Hive Mind: Popcorn (no runnable "+") is copied as its regular ability (+20 own, +20 copy)', function()
    run({ 'popcorn' })
    T.eq(compat(), 'compatible')
    T.eq(pair2().mult, 2 + 20 + 20)
end)
T.test('Hive Mind: Nacho Chips ("+" Popcorn) is copied as it is (+50 own, +50 copy)', function()
    run({ 'bplus_popcorn_plus' })
    T.eq(pair2().mult, 2 + 50 + 50)
end)
T.test('Hive Mind: Ice Cream is copied as its regular ability (+100 Chips own, +100 copy)', function()
    run({ 'ice_cream' })
    T.eq(pair2().chips, 10 + 2 + 2 + 100 + 100)
end)
T.test('Hive Mind: copies the "+" ability of vanilla Abstract Joker (+10 per Joker, 2 Jokers)', function()
    run({ 'abstract' })
    -- own +3 per Joker, copy +10 per Joker; 2 Jokers (the copier counts)
    T.eq(pair2().mult, 2 + 3 * 2 + 10 * 2)
end)
T.test('Hive Mind: copies Abstract Abstract Joker as it is', function()
    run({ 'bplus_abstract_plus' })
    T.eq(pair2().mult, 2 + 10 * 2 + 10 * 2)
end)

-- B7 Green Joker (growing and shrinking)
T.test('Hive Mind: copies vanilla Green Joker as Evergreen (stored value, no growth from the copy)', function()
    run({ 'green_joker' }, { hands = 5 })
    -- hand 1: Green gains +1 (stored 1); own +1, copy +1
    T.eq(pair2().mult, 2 + 1 + 1)
    T.eq(T.joker('green_joker').ability.mult, 1)
    T.eq(pair2().mult, 2 + 2 + 2)
    T.eq(T.joker('green_joker').ability.mult, 2, 'the copy did not gain')
end)
T.test('Hive Mind: copies Evergreen Joker (no growth from the copy)', function()
    run({ 'bplus_green_joker_plus' }, { hands = 5 })
    T.eq(pair2().mult, 2 + 2 + 2)
    T.eq(T.joker('bplus_green_joker_plus').ability.extra.mult, 2)
    T.eq(pair2().mult, 2 + 4 + 4)
    T.eq(T.joker('bplus_green_joker_plus').ability.extra.mult, 4)
end)

-- B8 Seance: card creation through the copy
local function spectrals()
    local n = 0
    for _, c in ipairs(G.consumeables.cards) do if c.ability.set == 'Spectral' then n = n + 1 end end
    return n
end
T.test('Hive Mind: copies the "+" ability of vanilla Seance (2 Spectrals from the copy + 1 own)', function()
    run({ 'seance' }, { consumable_slots = 4 })
    T.set_hand({ '9S', '8S', '7S', '6S', '5S' })
    T.eq(T.play({ '9S', '8S', '7S', '6S', '5S' }).hand, 'Straight Flush')
    T.eq(spectrals(), 2 + 1)
end)
T.test('Hive Mind: copies Spirit Board as it is (2 + 2 Spectrals)', function()
    run({ 'bplus_seance_plus' }, { consumable_slots = 4 })
    T.set_hand({ '9S', '8S', '7S', '6S', '5S' })
    T.play({ '9S', '8S', '7S', '6S', '5S' })
    T.eq(spectrals(), 2 + 2)
end)

-- B9 Sock and Buskin (retriggers); Oops! All 6s makes the "+" chance certain
T.test('Hive Mind: copies the "+" retriggers of vanilla Sock and Buskin (1 own + 1 copy)', function()
    run({ 'sock_and_buskin', 'oops' })
    T.set_hand({ 'KS', '9H' })
    -- vanilla retrigger +1; the copied "+" retrigger is 1 + 1 (certain bonus) = 2
    T.eq(T.play({ 'KS' }).chips, 5 + 10 * (1 + 1 + 2))
end)
T.test('Hive Mind: copies Melpomene and Thalia as it is', function()
    run({ 'bplus_sock_and_buskin_plus', 'oops' })
    T.set_hand({ 'KS', '9H' })
    T.eq(T.play({ 'KS' }).chips, 5 + 10 * (1 + 2 + 2))
end)

-- B10 Canio (growing, destroys cards)
local function destroy_faces()
    T.set_hand({ 'KS', 'QH', '7C', '5D', '3D', '2C', '4S', '6H' })
    T.use('hanged_man', { 'KS', 'QH' })
end
T.test('Hive Mind: copies vanilla Canio as Canio+ with the stored value, without gaining', function()
    run({ 'caino' }, { consumables = { 'hanged_man' } })
    destroy_faces()
    T.eq(T.joker('caino').ability.caino_xmult, 1 + 2, 'only the original grows (X1 per face)')
    T.eq(pair2().mult, 2 * 3 * 3)
end)
T.test('Hive Mind: copies Canio+ with its stored value, without gaining', function()
    run({ 'bplus_caino_plus' }, { consumables = { 'hanged_man' } })
    destroy_faces()
    T.eq(T.joker('bplus_caino_plus').ability.extra.Xmult, 1 + 2 * 2)
    T.eq(pair2().mult, 2 * 5 * 5)
end)

-- Rule 3 and 4
T.test('Hive Mind: Gros Michel (no "+" version) is copied as its regular ability (+15 own, +15 copy)', function()
    T.truthy(BPlus.upgrade_map.j_gros_michel == nil, 'Gros Michel has no "+" version (revisit this test if one is added)')
    run({ 'gros_michel' })
    T.eq(compat(), 'compatible')
    T.eq(pair2().mult, 2 + 15 + 15)
end)
T.test('Hive Mind: Four Fingers (not Blueprint-compatible) is incompatible', function()
    run({ 'four_fingers' })
    T.eq(compat(), 'incompatible')
    T.eq(pair2().mult, 2)
end)
T.test('Hive Mind: Carpenter is incompatible', function()
    run({ 'carpenter' })
    T.eq(compat(), 'incompatible')
    T.eq(pair2().mult, 2)
end)
T.test('Hive Mind: a "+" joker that is not Blueprint-compatible (Knife Juggler+) is incompatible', function()
    run({ 'bplus_juggler_plus' })
    T.eq(compat(), 'incompatible')
    T.eq(pair2().mult, 2)
end)
T.test('Hive Mind: vanilla Knife Juggler (neither version compatible) is incompatible', function()
    run({ 'juggler' })
    T.eq(compat(), 'incompatible')
end)
T.test('Hive Mind: a debuffed target is not copied', function()
    run({ 'joker' })
    T.joker('joker'):set_debuff(true)
    T.eq(pair2().mult, 2)
end)

-- Plain checks of the lineup rule
T.test('Hive Mind: vanilla Joker next to it -> +20 (Joker+), own +4', function()
    run({ 'joker' })
    T.eq(pair2().mult, 2 + 4 + 20)
end)
T.test('Hive Mind: Joker+ next to it -> +20 own, +20 copy', function()
    run({ 'bplus_joker_plus' })
    T.eq(pair2().mult, 2 + 20 + 20)
end)

-- The Rust: behaves as vanilla Brainstorm (copies the plain ability)
T.test('Hive Mind: forced to base (The Rust) copies the plain ability of Joker (+4)', function()
    run({ 'joker' })
    T.force_behavior(COPIER, 'base')
    T.eq(pair2().mult, 2 + 4 + 4)
end)
T.test('Hive Mind: forced to base (The Rust) copies a "+" joker as it is (+20)', function()
    run({ 'bplus_joker_plus' })
    T.force_behavior(COPIER, 'base')
    T.eq(pair2().mult, 2 + 20 + 20)
end)
T.test('Hive Mind: forced to base (The Rust) cannot copy a Blueprint-incompatible Joker', function()
    run({ 'juggler' })
    T.force_behavior(COPIER, 'base')
    T.eq(pair2().mult, 2)
end)

-- vanilla Brainstorm forced to "+" (what Carpenter does) behaves as Hive Mind
T.test('Hive Mind: vanilla Brainstorm forced to "+" copies the "+" ability of Joker', function()
    T.start_run({ jokers = { 'joker', 'brainstorm' }, ante = 3 })
    T.select_blind()
    T.force_behavior('brainstorm', 'plus')
    T.eq(pair2().mult, 2 + 4 + 20)
end)

-- JokerDisplay
T.test('Hive Mind JokerDisplay: next to vanilla Joker shows the "+" display (+20, not +4)', function()
    run({ 'joker' })
    T.joker_display('joker')
    T.eq(T.joker_display(COPIER).text, '+20')
    T.eq(T.joker_display('joker').text, '+4')
end)
T.test('Hive Mind JokerDisplay: next to Joker+ shows +20; incompatible target shows (incompatible)', function()
    run({ 'bplus_joker_plus' })
    T.joker_display('bplus_joker_plus')
    T.eq(T.joker_display(COPIER).text, '+20')
    local fresh = T.start_run({ jokers = lineup({ 'four_fingers' }), ante = 3 })
    T.eq(T.joker_display(COPIER).reminder, '(incompatible)')
end)
T.test('Hive Mind JokerDisplay: Abstract shows its "+" number (+10 per Joker); Popcorn shows its regular number', function()
    run({ 'abstract' })
    T.joker_display('abstract')
    T.eq(T.joker_display(COPIER).text, '+' .. 10 * 2)
    T.start_run({ jokers = lineup({ 'popcorn' }), ante = 3 })
    T.joker_display('popcorn')
    T.eq(T.joker_display(COPIER).text, '+20')
end)
T.test('Hive Mind JokerDisplay: forced to base shows the vanilla number (+4 next to Joker)', function()
    run({ 'joker' })
    T.joker_display('joker')
    T.force_behavior(COPIER, 'base')
    T.eq(T.joker_display(COPIER).text, '+4')
end)
