local T = BPlus.test

T.test('Executive Card: with Oops! All 6s, score 2 face cards -> +$3 + $3 (vanilla: +$2 + $2)', function()
    T.start_run({ ante = 3, dollars = 0, jokers = { 'bplus_business_plus', 'oops' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.dollars, 3 + 3)
end)

T.test('Executive Card: score a 7 -> $0', function()
    T.start_run({ ante = 3, dollars = 0, jokers = { 'bplus_business_plus', 'oops' } })
    T.select_blind()
    T.set_hand({ '7S' })
    local r = T.play({ '7S' })
    T.eq(r.dollars, 0)
end)

T.test('Executive Card: vanilla Business Card forced to "+" with Oops! -> $3 + $3', function()
    T.start_run({ ante = 3, dollars = 0, jokers = { 'business', 'oops' } })
    T.force_behavior('business', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.dollars, 3 + 3)
end)

T.test('Executive Card JokerDisplay: 0x$3 (1 in 2); vanilla forced to "+" 0x$3; "+" forced to base 0x$2', function()
    T.start_run({ dollars = 6, jokers = { 'bplus_business_plus', 'business' } })
    local d = T.joker_display('bplus_business_plus')
    T.eq(d.text, '0x$3')
    T.eq(d.extra[1], '(1 in 2)')
    T.eq(T.joker_display('business').text, '0x$2')
    T.force_behavior('business', 'plus')
    T.eq(T.joker_display('business').text, '0x$3')
    T.force_behavior('bplus_business_plus', 'base')
    T.eq(T.joker_display('bplus_business_plus').text, '0x$2')
end)
