local T = BPlus.test

T.test('Golden Bull: with $20 -> +5 * 20 Chips', function()
    T.start_run({ jokers = { 'bplus_bull_plus' }, ante = 3, dollars = 20 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 5 * 20)
    T.eq(r.mult, 1)
end)

T.test('Golden Bull: in debt -> no effect', function()
    T.start_run({ jokers = { 'bplus_bull_plus', 'credit_card' }, ante = 3, dollars = -5 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11)
    T.eq(r.mult, 1)
end)

T.test('Golden Bull: vanilla forced to "+" matches (vanilla 1, "+" 1 mult)', function()
    T.start_run({ jokers = { 'bull' }, ante = 3, dollars = 20 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    T.force_behavior('bull', 'plus')
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 5 * 20)
    T.eq(r.mult, 1)
end)

T.test('Golden Bull: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'bull' }, ante = 3, dollars = 20 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 2 * 20)
    T.eq(r.mult, 1)
end)

T.test('Golden Bull JokerDisplay: "+" shows the "+" numbers; vanilla forced to "+" shows them too; "+" forced to base shows vanilla numbers', function()
    T.start_run({ ante = 4, jokers = { 'bplus_bull_plus', 'bull' } })
    T.select_blind()
    local d = T.joker_display('bplus_bull_plus')
    T.eq(d.text, '+' .. (5 * G.GAME.dollars))
    T.eq(T.joker_display('bull').text, '+' .. (2 * G.GAME.dollars))
    T.force_behavior('bull', 'plus')
    T.eq(T.joker_display('bull').text, '+' .. (5 * G.GAME.dollars))
    T.force_behavior('bplus_bull_plus', 'base')
    T.eq(T.joker_display('bplus_bull_plus').text, '+' .. (2 * G.GAME.dollars))
end)
