local T = BPlus.test

T.test('Clairvoyant: select Blind -> 1 Tarot', function()
    T.start_run({ ante = 3, jokers = { 'bplus_cartomancer_plus' } })
    T.select_blind()
    T.eq(#G.consumeables.cards, 1)
    T.eq(G.consumeables.cards[1].ability.set, 'Tarot')
end)

T.test('Clairvoyant: win the round -> 1 more Tarot', function()
    T.start_run({ ante = 3, jokers = { 'bplus_cartomancer_plus' } })
    T.select_blind()
    T.eq(#G.consumeables.cards, 1)
    T.win_blind()
    T.eq(#G.consumeables.cards, 1 + 1)
end)

T.test('Clairvoyant: slots full -> nothing created', function()
    T.start_run({ ante = 3, consumables = { 'pluto', 'mercury' }, jokers = { 'bplus_cartomancer_plus' } })
    T.select_blind()
    T.eq(#G.consumeables.cards, 2)
    T.win_blind()
    T.eq(#G.consumeables.cards, 2)
    T.eq(G.consumeables.cards[1].ability.set, 'Planet')
end)

T.test('Clairvoyant: vanilla Cartomancer forced to "+" also makes a Tarot on win', function()
    T.start_run({ ante = 3, jokers = { 'cartomancer' } })
    T.force_behavior('cartomancer', 'plus')
    T.select_blind()
    T.eq(#G.consumeables.cards, 1)
    T.win_blind()
    T.eq(#G.consumeables.cards, 1 + 1)
end)

T.test('Clairvoyant JokerDisplay: shows nothing (vanilla definition is empty)', function()
    T.start_run({ dollars = 6, jokers = { 'bplus_cartomancer_plus', 'cartomancer' } })
    T.eq(T.joker_display('bplus_cartomancer_plus').text, '')
    T.force_behavior('cartomancer', 'plus')
    T.eq(T.joker_display('cartomancer').text, '')
    T.force_behavior('bplus_cartomancer_plus', 'base')
    T.eq(T.joker_display('bplus_cartomancer_plus').text, '')
end)
