local T = BPlus.test

local function destroy_faces()
    T.set_hand({ 'KS', 'QH', '7C', '5D', '3D', '2C', '4S', '6H' })
    T.use('hanged_man', { 'KS', 'QH' })
end

T.test('Canio+: destroy 2 face cards -> X(1 + 2 * 2) = X5 (vanilla: X3)', function()
    T.start_run({ jokers = { 'bplus_caino_plus' }, consumables = { 'hanged_man' }, ante = 3 })
    T.select_blind()
    destroy_faces()
    T.eq(T.joker(1).ability.extra.Xmult, 1 + 2 * 2)
    T.set_hand({ '2S', '2H', '7C', '5D', '3D' })
    local r = T.play({ '2S', '2H' })
    T.eq(r.chips, 10 + 2 + 2)
    T.eq(r.mult, 2 * (1 + 2 * 2))
end)

T.test('Canio+: vanilla Canio gains only X1 per face card (X3)', function()
    T.start_run({ jokers = { 'caino' }, consumables = { 'hanged_man' }, ante = 3 })
    T.select_blind()
    destroy_faces()
    T.eq(T.joker(1).ability.caino_xmult, 1 + 2 * 1)
end)

T.test('Canio+: Canio at X3, upgrade -> Canio+ keeps X3, next face card destroyed: X(3 + 2) = X5', function()
    T.start_run({ jokers = { { key = 'caino', edition = 'foil' } }, consumables = { 'hanged_man', 'hanged_man' }, ante = 3 })
    T.select_blind()
    destroy_faces()
    T.eq(T.joker(1).ability.caino_xmult, 1 + 2 * 1)
    local card = T.upgrade('caino')
    T.eq(card.ability.extra.Xmult, 3)
    T.truthy(card.edition and card.edition.foil, 'foil kept')
    T.set_hand({ 'KS', '8H', '7C', '5D', '3D', '2C', '4S', '6H' })
    T.use('hanged_man', { 'KS' })
    T.eq(card.ability.extra.Xmult, 3 + 2)
end)

T.test('Canio+: vanilla Canio forced to "+" gains X2 per face card and keeps its value', function()
    T.start_run({ jokers = { 'caino' }, consumables = { 'hanged_man' }, ante = 3 })
    T.select_blind()
    T.force_behavior('caino', 'plus')
    destroy_faces()
    T.eq(T.joker(1).ability.caino_xmult, 1 + 2 * 2)
end)

T.test('Canio+: Canio+ forced to base gains X1 per face card and keeps its value', function()
    T.start_run({ jokers = { 'bplus_caino_plus' }, consumables = { 'hanged_man', 'hanged_man' }, ante = 3 })
    T.select_blind()
    destroy_faces()
    T.eq(T.joker(1).ability.extra.Xmult, 5)
    T.force_behavior(1, 'base')
    T.set_hand({ 'KS', '8H', '7C', '5D', '3D', '2C', '4S', '6H' })
    T.use('hanged_man', { 'KS' })
    T.eq(T.joker(1).ability.extra.Xmult, 5 + 1)
end)

T.test('Canio+ JokerDisplay: X5 after 2 faces destroyed (vanilla X3); forced behaviours keep the stored value', function()
    T.start_run({ jokers = { 'bplus_caino_plus', 'caino' }, consumables = { 'hanged_man' }, ante = 3 })
    T.select_blind()
    T.eq(T.joker_display('bplus_caino_plus').text, 'X1')
    destroy_faces()
    T.eq(T.joker_display('bplus_caino_plus').text, 'X' .. (1 + 2 * 2))
    T.eq(T.joker_display('caino').text, 'X' .. (1 + 2))
    T.force_behavior('caino', 'plus')
    T.eq(T.joker_display('caino').text, 'X' .. (1 + 2))
    T.force_behavior('bplus_caino_plus', 'base')
    T.eq(T.joker_display('bplus_caino_plus').text, 'X' .. (1 + 2 * 2))
end)
