local T = BPlus.test

-- Four Fingers (cost $7) sells for $3, so it is a convenient victim.
local function next_blind()
    T.win_blind()
    T.cash_out()
    T.leave_shop()
end

T.test('Sacrificial Dagger: Joker to the right sells for $3, select Blind -> destroyed, Mult = 0 + 3 * 3 = 9 (vanilla: 2 * 3 = 6)', function()
    T.start_run({ jokers = { 'bplus_ceremonial_plus', 'four_fingers' }, ante = 3 })
    local victim = T.joker(2)
    T.eq(victim.sell_cost, 3)
    T.select_blind()
    T.falsy(T.joker('four_fingers'), 'victim destroyed')
    T.eq(T.joker(1).ability.extra.mult, 0 + 3 * 3)
    T.eq(T.play({ 1 }).mult, 1 + 9)
end)

T.test('Sacrificial Dagger: vanilla Ceremonial Dagger adds double the sell value', function()
    T.start_run({ jokers = { 'ceremonial', 'four_fingers' }, ante = 3 })
    T.select_blind()
    T.falsy(T.joker('four_fingers'), 'victim destroyed')
    T.eq(T.joker(1).ability.mult, 0 + 2 * 3)
    T.eq(T.play({ 1 }).mult, 1 + 6)
end)

T.test('Sacrificial Dagger: Eternal joker to the right -> nothing happens', function()
    T.start_run({ jokers = { 'bplus_ceremonial_plus', { key = 'four_fingers', stickers = { 'eternal' } } }, ante = 3 })
    T.select_blind()
    T.truthy(T.joker('four_fingers'), 'eternal joker survives')
    T.eq(T.joker(1).ability.extra.mult, 0)
    T.eq(T.play({ 1 }).mult, 1)
end)

T.test("Sacrificial Dagger: Ceremonial Dagger at +6 Mult, upgrade -> keeps +6 Mult, later gains use the '+' rate", function()
    T.start_run({ jokers = { { key = 'ceremonial', edition = 'foil' }, 'four_fingers', 'four_fingers' }, ante = 3 })
    T.select_blind()
    T.eq(T.joker(1).ability.mult, 2 * 3, 'vanilla value')
    next_blind()
    local card = T.upgrade('ceremonial')
    T.eq(card.ability.extra.mult, 2 * 3, 'carried over')
    T.truthy(card.edition and card.edition.foil, 'foil kept')
    T.select_blind()
    T.falsy(T.joker('four_fingers'), 'second victim destroyed')
    T.eq(card.ability.extra.mult, 6 + 3 * 3)
    T.eq(T.play({ 1 }).mult, 1 + 15)
end)

T.test('Sacrificial Dagger: vanilla Dagger forced to "+" gains triple, stored on the vanilla field', function()
    T.start_run({ jokers = { 'ceremonial', 'four_fingers' }, ante = 3 })
    T.force_behavior('ceremonial', 'plus')
    T.select_blind()
    T.eq(T.joker(1).ability.mult, 3 * 3)
    T.eq(T.play({ 1 }).mult, 1 + 9)
end)

T.test('Sacrificial Dagger: forced to base keeps its value, gains double', function()
    T.start_run({ jokers = { 'bplus_ceremonial_plus', 'four_fingers', 'four_fingers' }, ante = 3 })
    T.select_blind()
    T.eq(T.joker(1).ability.extra.mult, 9)
    next_blind()
    T.force_behavior(1, 'base')
    T.select_blind()
    T.eq(T.joker(1).ability.extra.mult, 9 + 2 * 3)
end)

T.test('Sacrificial Dagger JokerDisplay: +3 * 3 = +9; vanilla +2 * 3 = +6; stored values kept when forced to "+" / base', function()
    T.start_run({ jokers = { 'ceremonial', 'four_fingers', 'bplus_ceremonial_plus', 'four_fingers' }, ante = 3 })
    T.select_blind()
    T.eq(T.joker_display('bplus_ceremonial_plus').text, '+' .. (3 * 3))
    T.eq(T.joker_display('ceremonial').text, '+' .. (2 * 3))
    T.force_behavior('ceremonial', 'plus')
    T.eq(T.joker_display('ceremonial').text, '+' .. (2 * 3))
    T.force_behavior('bplus_ceremonial_plus', 'base')
    T.eq(T.joker_display('bplus_ceremonial_plus').text, '+' .. (3 * 3))
end)
