local T = BPlus.test

T.test('Brainy Joker: play a Two Pair -> +140 Chips (vanilla: +80 Chips)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_clever_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', '4D', '4S' })
    T.eq(r.hand, 'Two Pair')
    T.eq(r.chips, 48 + 140)
    T.eq(r.mult, 2)
end)

T.test('Brainy Joker: vanilla joker plays a Two Pair -> +80 Chips', function()
    T.start_run({ ante = 4, jokers = { 'clever' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', '4D', '4S' })
    T.eq(r.hand, 'Two Pair')
    T.eq(r.chips, 48 + 80)
    T.eq(r.mult, 2)
end)

T.test('Brainy Joker: play a Full House (contains a Two Pair) -> +140 Chips', function()
    T.start_run({ ante = 4, jokers = { 'bplus_clever_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78 + 140)
    T.eq(r.mult, 4)
end)

T.test('Brainy Joker: play a Pair -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_clever_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2)
end)

T.test('Brainy Joker: vanilla joker forced to "+" plays a Two Pair -> +140 Chips', function()
    T.start_run({ ante = 4, jokers = { 'clever' } })
    T.force_behavior('clever', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', '4D', '4S' })
    T.eq(r.hand, 'Two Pair')
    T.eq(r.chips, 48 + 140)
    T.eq(r.mult, 2)
end)
