local T = BPlus.test

T.test('Shrewd Joker: play a Flush -> +140 Chips (vanilla: +80 Chips)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crafty_plus' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70 + 140)
    T.eq(r.mult, 4)
end)

T.test('Shrewd Joker: vanilla joker plays a Flush -> +80 Chips', function()
    T.start_run({ ante = 4, jokers = { 'crafty' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70 + 80)
    T.eq(r.mult, 4)
end)

T.test('Shrewd Joker: play a Straight Flush (contains a Flush) -> +140 Chips', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crafty_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135 + 140)
    T.eq(r.mult, 8)
end)

T.test('Shrewd Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crafty_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Shrewd Joker: vanilla joker forced to "+" plays a Flush -> +140 Chips', function()
    T.start_run({ ante = 4, jokers = { 'crafty' } })
    T.force_behavior('crafty', 'plus')
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70 + 140)
    T.eq(r.mult, 4)
end)

T.test('Shrewd Joker JokerDisplay: shows +140 (Flush) with a Flush selected, +0 without; vanilla forced to "+" shows +140; "+" forced to base shows +80', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crafty_plus', 'crafty' } })
    T.select_blind()
    T.set_hand({ '2H','5H','7H','9H','JH' })
    local d = T.joker_display('bplus_crafty_plus')
    T.eq(d.text, '+0')
    T.eq(d.reminder, '(Flush)')
    T.highlight({ 1, 2, 3, 4, 5 })
    T.eq(T.joker_display('bplus_crafty_plus').text, '+140')
    T.eq(T.joker_display('crafty').text, '+80')
    T.force_behavior('crafty', 'plus')
    T.eq(T.joker_display('crafty').text, '+140')
    T.force_behavior('bplus_crafty_plus', 'base')
    T.eq(T.joker_display('bplus_crafty_plus').text, '+80')
end)
