local T = BPlus.test

T.test('Wacky Joker: play a Straight -> +32 Mult (vanilla: +12 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crazy_plus' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 + 32)
end)

T.test('Wacky Joker: vanilla joker plays a Straight -> +12 Mult', function()
    T.start_run({ ante = 4, jokers = { 'crazy' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 + 12)
end)

T.test('Wacky Joker: play a Straight Flush (contains a Straight) -> +32 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crazy_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135)
    T.eq(r.mult, 8 + 32)
end)

T.test('Wacky Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crazy_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Wacky Joker: vanilla joker forced to "+" plays a Straight -> +32 Mult', function()
    T.start_run({ ante = 4, jokers = { 'crazy' } })
    T.force_behavior('crazy', 'plus')
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 + 32)
end)
