local T = BPlus.test

T.test('Wacky Joker: play a Straight -> +32 Mult (vanilla: +12 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crazy_plus' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 + 32)
end)

T.test('Wacky Joker: vanilla joker plays a Straight -> +12 Mult', function()
    T.start_run({ ante = 4, jokers = { 'crazy' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 + 12)
end)

T.test('Wacky Joker: play a Straight Flush (contains a Straight) -> +32 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crazy_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135)
    T.eq(r.mult, 8 + 32)
end)

T.test('Wacky Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crazy_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Wacky Joker: vanilla joker forced to "+" plays a Straight -> +32 Mult', function()
    T.start_run({ ante = 4, jokers = { 'crazy' } })
    T.force_behavior('crazy', 'plus')
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 + 32)
end)

T.test('Wacky Joker JokerDisplay: shows +32 (Straight) with a Straight selected, +0 without; vanilla forced to "+" shows +32; "+" forced to base shows +12', function()
    T.start_run({ ante = 4, jokers = { 'bplus_crazy_plus', 'crazy' } })
    T.select_blind()
    T.set_hand({ '5S','6H','7C','8D','9S' })
    local d = T.joker_display('bplus_crazy_plus')
    T.eq(d.text, '+0')
    T.eq(d.reminder, '(Straight)')
    T.highlight({ 1, 2, 3, 4, 5 })
    T.eq(T.joker_display('bplus_crazy_plus').text, '+32')
    T.eq(T.joker_display('crazy').text, '+12')
    T.force_behavior('crazy', 'plus')
    T.eq(T.joker_display('crazy').text, '+32')
    T.force_behavior('bplus_crazy_plus', 'base')
    T.eq(T.joker_display('bplus_crazy_plus').text, '+12')
end)
