local T = BPlus.test

T.test('Insidious Joker: play a Straight -> +200 Chips (vanilla: +100 Chips)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_devious_plus' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65 + 200)
    T.eq(r.mult, 4)
end)

T.test('Insidious Joker: vanilla joker plays a Straight -> +100 Chips', function()
    T.start_run({ ante = 4, jokers = { 'devious' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65 + 100)
    T.eq(r.mult, 4)
end)

T.test('Insidious Joker: play a Straight Flush (contains a Straight) -> +200 Chips', function()
    T.start_run({ ante = 4, jokers = { 'bplus_devious_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135 + 200)
    T.eq(r.mult, 8)
end)

T.test('Insidious Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_devious_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Insidious Joker: vanilla joker forced to "+" plays a Straight -> +200 Chips', function()
    T.start_run({ ante = 4, jokers = { 'devious' } })
    T.force_behavior('devious', 'plus')
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65 + 200)
    T.eq(r.mult, 4)
end)
