local T = BPlus.test

T.test('Instant Gratification: 3 discards left, none used -> $2 * 3 = $6 (same as vanilla)', function()
    T.start_run({ dollars = 0, discards = 3, jokers = { 'bplus_delayed_grat_plus' } })
    T.select_blind()
    T.win_blind()
    T.eq(T.cash_out(), 3 + 4 + 2 * 3)
end)

T.test('Instant Gratification: use 1 of 3 discards -> $2 * 2 = $4 (vanilla: $0)', function()
    T.start_run({ dollars = 0, discards = 3, jokers = { 'bplus_delayed_grat_plus' } })
    T.select_blind()
    T.discard({ 1 })
    T.win_blind()
    T.eq(T.cash_out(), 3 + 4 + 2 * 2)
end)

T.test('Instant Gratification: vanilla pays $0 after a discard', function()
    T.start_run({ dollars = 0, discards = 3, jokers = { 'delayed_grat' } })
    T.select_blind()
    T.discard({ 1 })
    T.win_blind()
    T.eq(T.cash_out(), 3 + 4)
end)

T.test('Instant Gratification: 0 discards left -> $0', function()
    T.start_run({ dollars = 0, discards = 1, jokers = { 'bplus_delayed_grat_plus' } })
    T.select_blind()
    T.discard({ 1 })
    T.win_blind()
    T.eq(T.cash_out(), 3 + 4)
end)

T.test('Instant Gratification: Delayed Gratification forced to "+" pays after a discard', function()
    T.start_run({ dollars = 0, discards = 3, jokers = { 'delayed_grat' } })
    T.force_behavior('delayed_grat', 'plus')
    T.select_blind()
    T.discard({ 1 })
    T.win_blind()
    T.eq(T.cash_out(), 3 + 4 + 2 * 2)
end)
