local T = BPlus.test

T.test('Insidious Joker: play a Straight -> +200 Chips (vanilla: +100 Chips)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_devious_plus' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65 + 200)
    T.eq(r.mult, 4)
end)

T.test('Insidious Joker: vanilla joker plays a Straight -> +100 Chips', function()
    T.start_run({ ante = 4, jokers = { 'devious' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65 + 100)
    T.eq(r.mult, 4)
end)

T.test('Insidious Joker: play a Straight Flush (contains a Straight) -> +200 Chips', function()
    T.start_run({ ante = 4, jokers = { 'bplus_devious_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135 + 200)
    T.eq(r.mult, 8)
end)

T.test('Insidious Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_devious_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Insidious Joker: vanilla joker forced to "+" plays a Straight -> +200 Chips', function()
    T.start_run({ ante = 4, jokers = { 'devious' } })
    T.force_behavior('devious', 'plus')
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65 + 200)
    T.eq(r.mult, 4)
end)

T.test('Insidious Joker JokerDisplay: shows +200 (Straight) with a Straight selected, +0 without; vanilla forced to "+" shows +200; "+" forced to base shows +100', function()
    T.start_run({ ante = 4, jokers = { 'bplus_devious_plus', 'devious' } })
    T.select_blind()
    T.set_hand({ '5S','6H','7C','8D','9S' })
    local d = T.joker_display('bplus_devious_plus')
    T.eq(d.text, '+0')
    T.eq(d.reminder, '(Straight)')
    G.hand:unhighlight_all()
    for _, c in ipairs(G.hand.cards) do G.hand:add_to_highlighted(c, true) end
    T.eq(T.joker_display('bplus_devious_plus').text, '+200')
    T.eq(T.joker_display('devious').text, '+100')
    T.force_behavior('devious', 'plus')
    T.eq(T.joker_display('devious').text, '+200')
    T.force_behavior('bplus_devious_plus', 'base')
    T.eq(T.joker_display('bplus_devious_plus').text, '+100')
end)
