local T = BPlus.test

T.test('Wry Joker: play a Flush -> +25 Mult (vanilla: +10 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_droll_plus' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 + 25)
end)

T.test('Wry Joker: vanilla joker plays a Flush -> +10 Mult', function()
    T.start_run({ ante = 4, jokers = { 'droll' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 + 10)
end)

T.test('Wry Joker: play a Straight Flush (contains a Flush) -> +25 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_droll_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135)
    T.eq(r.mult, 8 + 25)
end)

T.test('Wry Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_droll_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Wry Joker: vanilla joker forced to "+" plays a Flush -> +25 Mult', function()
    T.start_run({ ante = 4, jokers = { 'droll' } })
    T.force_behavior('droll', 'plus')
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 + 25)
end)
