local T = BPlus.test

T.test('The Dynamic Duo: play a Pair -> X3 Mult (vanilla: X2 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_duo_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 * 3)
end)

T.test('The Dynamic Duo: vanilla joker plays a Pair -> X2 Mult', function()
    T.start_run({ ante = 4, jokers = { 'duo' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 * 2)
end)

T.test('The Dynamic Duo: play a Full House (contains a Pair) -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_duo_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78)
    T.eq(r.mult, 4 * 3)
end)

T.test('The Dynamic Duo: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_duo_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('The Dynamic Duo: vanilla joker forced to "+" plays a Pair -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'duo' } })
    T.force_behavior('duo', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 * 3)
end)

T.test('The Dynamic Duo JokerDisplay: shows X3 (Pair) with a Pair selected, X1 without; vanilla forced to "+" shows X3; "+" forced to base shows X2', function()
    T.start_run({ ante = 4, jokers = { 'bplus_duo_plus', 'duo' } })
    T.select_blind()
    T.set_hand({ 'KS','KH' })
    local d = T.joker_display('bplus_duo_plus')
    T.eq(d.text, 'X1')
    T.eq(d.reminder, '(Pair)')
    G.hand:unhighlight_all()
    for _, c in ipairs(G.hand.cards) do G.hand:add_to_highlighted(c, true) end
    T.eq(T.joker_display('bplus_duo_plus').text, 'X3')
    T.eq(T.joker_display('duo').text, 'X2')
    T.force_behavior('duo', 'plus')
    T.eq(T.joker_display('duo').text, 'X3')
    T.force_behavior('bplus_duo_plus', 'base')
    T.eq(T.joker_display('bplus_duo_plus').text, 'X2')
end)
