local T = BPlus.test

T.test('Steven the Even: 10s and 4s -> +8 Mult each (vanilla: +4)', function()
    T.start_run({ jokers = { 'bplus_even_steven_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '10S', '10H', '4S', '4H', '9C' })
    local r = T.play({ '10S', '10H', '4S', '4H' })
    T.eq(r.chips, 20 + 10 + 10 + 4 + 4)
    T.eq(r.mult, 2 + 8 + 8 + 8 + 8)
end)

T.test('Steven the Even: scoring a Queen -> no effect', function()
    T.start_run({ jokers = { 'bplus_even_steven_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'QS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'QS' })
    T.eq(r.chips, 5 + 10)
    T.eq(r.mult, 1)
end)

T.test('Steven the Even: vanilla forced to "+" matches (vanilla 2 + 4 + 4 + 4 + 4, "+" 2 + 8 + 8 + 8 + 8 mult)', function()
    T.start_run({ jokers = { 'even_steven' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '10S', '10H', '4S', '4H', '9C' })
    T.force_behavior('even_steven', 'plus')
    local r = T.play({ '10S', '10H', '4S', '4H' })
    T.eq(r.chips, 20 + 10 + 10 + 4 + 4)
    T.eq(r.mult, 2 + 8 + 8 + 8 + 8)
end)

T.test('Steven the Even: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'even_steven' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '10S', '10H', '4S', '4H', '9C' })
    local r = T.play({ '10S', '10H', '4S', '4H' })
    T.eq(r.chips, 20 + 10 + 10 + 4 + 4)
    T.eq(r.mult, 2 + 4 + 4 + 4 + 4)
end)
