local T = BPlus.test

T.test('Jackson Joker: play a Four of a Kind -> X5 Mult (vanilla: X4 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_family_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', 'KD' })
    local r = T.play({ 'KS', 'KH', 'KC', 'KD' })
    T.eq(r.hand, 'Four of a Kind')
    T.eq(r.chips, 100)
    T.eq(r.mult, 7 * 5)
end)

T.test('Jackson Joker: vanilla joker plays a Four of a Kind -> X4 Mult', function()
    T.start_run({ ante = 4, jokers = { 'family' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', 'KD' })
    local r = T.play({ 'KS', 'KH', 'KC', 'KD' })
    T.eq(r.hand, 'Four of a Kind')
    T.eq(r.chips, 100)
    T.eq(r.mult, 7 * 4)
end)

T.test('Jackson Joker: play a Five of a Kind (contains a Four of a Kind) -> X5 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_family_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', 'KD', 'KS' })
    local r = T.play({ 'KS', 'KH', 'KC', 'KD', 'KS' })
    T.eq(r.hand, 'Five of a Kind')
    T.eq(r.chips, 170)
    T.eq(r.mult, 12 * 5)
end)

T.test('Jackson Joker: play a Three of a Kind -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_family_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3)
end)

T.test('Jackson Joker: vanilla joker forced to "+" plays a Four of a Kind -> X5 Mult', function()
    T.start_run({ ante = 4, jokers = { 'family' } })
    T.force_behavior('family', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', 'KD' })
    local r = T.play({ 'KS', 'KH', 'KC', 'KD' })
    T.eq(r.hand, 'Four of a Kind')
    T.eq(r.chips, 100)
    T.eq(r.mult, 7 * 5)
end)
