local T = BPlus.test

T.test('Undercover Joker: discard 3 face cards -> +$6 (vanilla: +$5)', function()
    T.start_run({ dollars = 0, jokers = { 'bplus_faceless_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'QH', 'JD', '2C', '3C', '4C', '5C', '6C' })
    T.discard({ 'KS', 'QH', 'JD' })
    T.eq(G.GAME.dollars, 6)
end)

T.test('Undercover Joker: vanilla Faceless Joker pays $5', function()
    T.start_run({ dollars = 0, jokers = { 'faceless' } })
    T.select_blind()
    T.set_hand({ 'KS', 'QH', 'JD', '2C', '3C', '4C', '5C', '6C' })
    T.discard({ 'KS', 'QH', 'JD' })
    T.eq(G.GAME.dollars, 5)
end)

T.test('Undercover Joker: discard 2 face cards and a 7 -> $0', function()
    T.start_run({ dollars = 0, jokers = { 'bplus_faceless_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'QH', '7D', '2C', '3C', '4C', '5C', '6C' })
    T.discard({ 'KS', 'QH', '7D' })
    T.eq(G.GAME.dollars, 0)
end)

T.test('Undercover Joker: Faceless forced to "+" pays $6', function()
    T.start_run({ dollars = 0, jokers = { 'faceless' } })
    T.force_behavior('faceless', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'QH', 'JD', '2C', '3C', '4C', '5C', '6C' })
    T.discard({ 'KS', 'QH', 'JD' })
    T.eq(G.GAME.dollars, 6)
end)

-- Only sets the UI selection (nothing is played); JokerDisplay reads G.hand.highlighted.
local function highlight(specs)
    T.highlight(specs)
end

T.test('Undercover Joker JokerDisplay: +$0 -> 3 faces selected +$6; vanilla forced to "+" +$6; "+" forced to base +$5', function()
    T.start_run({ jokers = { 'bplus_faceless_plus', 'faceless' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KD', '5C', '5D', '2C', '3C', '4C' })
    T.eq(T.joker_display('bplus_faceless_plus').text, '+$0')
    highlight({ 'KS', 'KH', 'KD' })
    T.eq(T.joker_display('bplus_faceless_plus').text, '+$6')
    T.eq(T.joker_display('faceless').text, '+$5')
    T.force_behavior('faceless', 'plus')
    T.eq(T.joker_display('faceless').text, '+$6')
    T.force_behavior('bplus_faceless_plus', 'base')
    T.eq(T.joker_display('bplus_faceless_plus').text, '+$5')
end)
