local T = BPlus.test

T.test('Edacious Joker: Pair of Clubs -> +5 + 5 Mult (vanilla: +3 + 3)', function()
    T.start_run({ jokers = { 'bplus_gluttenous_joker_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KC', 'KC', '2H', '3H', '5H' })
    local r = T.play({ 1, 2 })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 10 + 10 + 10)
    T.eq(r.mult, 2 + 5 + 5)
end)

T.test('Edacious Joker: Pair with no Clubs -> +0 Mult', function()
    T.start_run({ jokers = { 'bplus_gluttenous_joker_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KH', 'KH', '2H', '3H', '5H' })
    local r = T.play({ 1, 2 })
    T.eq(r.mult, 2)
end)

T.test('Edacious Joker: vanilla gluttenous_joker gives +3 + 3 Mult', function()
    T.start_run({ jokers = { 'gluttenous_joker' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KC', 'KC', '2H', '3H', '5H' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 3 + 3)
end)

T.test('Edacious Joker: vanilla forced to "+" (Carpenter) gives +5 + 5 Mult', function()
    T.start_run({ jokers = { 'gluttenous_joker' }, ante = 3 })
    T.select_blind()
    T.force_behavior('gluttenous_joker', 'plus')
    T.set_hand({ 'KC', 'KC', '2H', '3H', '5H' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 5 + 5)
end)

T.test('Edacious Joker: "+" forced to base gives +3 + 3 Mult', function()
    T.start_run({ jokers = { 'bplus_gluttenous_joker_plus' }, ante = 3 })
    T.select_blind()
    T.force_behavior(1, 'base')
    T.set_hand({ 'KC', 'KC', '2H', '3H', '5H' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 3 + 3)
end)
