local T = BPlus.test

local function hand() return T.play({ 1 }) end

T.test('Evergreen Joker: play 3 hands -> +2 + 2 + 2 = 6 Mult', function()
    T.start_run({ jokers = { 'bplus_green_joker_plus' }, hands = 5, ante = 3 })
    T.select_blind()
    T.eq(hand().mult, 1 + 2)
    T.eq(hand().mult, 1 + 2 + 2)
    T.eq(hand().mult, 1 + 2 + 2 + 2)
    T.eq(T.joker(1).ability.extra.mult, 2 + 2 + 2)
end)

T.test('Evergreen Joker: then 1 discard -> 6 - 1 = 5 Mult', function()
    T.start_run({ jokers = { 'bplus_green_joker_plus' }, hands = 5, ante = 3 })
    T.select_blind()
    hand(); hand(); hand()
    T.discard({ 1 })
    T.eq(T.joker(1).ability.extra.mult, 2 + 2 + 2 - 1)
end)

T.test('Evergreen Joker: Mult never goes below 0', function()
    T.start_run({ jokers = { 'bplus_green_joker_plus' }, ante = 3 })
    T.select_blind()
    T.discard({ 1 })
    T.eq(T.joker(1).ability.extra.mult, 0)
    hand()
    T.discard({ 1 })
    T.eq(T.joker(1).ability.extra.mult, 2 - 1)
    T.discard({ 1 })
    T.eq(T.joker(1).ability.extra.mult, 0, 'clamped at 0 (2 - 1 - 1)')
end)

T.test("Evergreen Joker: Green Joker at +6 Mult, upgrade -> keeps +6 Mult, later gains use the '+' rate", function()
    T.start_run({ jokers = { { key = 'green_joker', edition = 'holo' } }, hands = 8, ante = 3 })
    T.select_blind()
    for _ = 1, 6 do hand() end
    T.eq(T.joker(1).ability.mult, 6, 'vanilla value')
    local card = T.upgrade('green_joker')
    T.eq(card.ability.extra.mult, 6, 'carried over')
    T.truthy(card.edition and card.edition.holo, 'holo kept')
    local r = hand()
    T.eq(card.ability.extra.mult, 6 + 2)
    T.eq(r.mult, 1 + 10 + 8)   -- base 1 + holo 10 + joker 8
end)

T.test('Evergreen Joker: Green Joker forced to "+" keeps its stored value, only the rate changes', function()
    T.start_run({ jokers = { 'green_joker' }, hands = 6, ante = 3 })
    T.select_blind()
    hand()
    T.eq(T.joker(1).ability.mult, 1)
    T.force_behavior('green_joker', 'plus')
    T.eq(hand().mult, 1 + 1 + 2)
    T.eq(T.joker(1).ability.mult, 1 + 2, 'stored on the vanilla card')
    T.force_behavior('green_joker', nil)
    T.eq(hand().mult, 1 + 3 + 1)
end)

T.test('Evergreen Joker: forced to base gains +1 per hand and keeps its value', function()
    T.start_run({ jokers = { 'bplus_green_joker_plus' }, hands = 6, ante = 3 })
    T.select_blind()
    hand()
    T.force_behavior(1, 'base')
    T.eq(hand().mult, 1 + 2 + 1)
    T.eq(T.joker(1).ability.extra.mult, 2 + 1)
    T.force_behavior(1, nil)
    T.eq(hand().mult, 1 + 3 + 2)
end)
