local T = BPlus.test

T.test('Defibrillator: play a Pair -> first scored card scores 1 + 3 = 4 times (vanilla: 3), second card once', function()
    T.start_run({ jokers = { 'bplus_hanging_chad_plus' } })
    T.select_blind()
    T.set_hand({ '9S', '9H', '2C', '5D', '3D' })
    local r = T.play({ '9S', '9H' })
    T.eq(r.chips, 10 + 9 * (1 + 3) + 9)
    T.eq(r.mult, 2)
end)

T.test('Hanging Chad (vanilla): first scored card scores 1 + 2 = 3 times', function()
    T.start_run({ jokers = { 'hanging_chad' } })
    T.select_blind()
    T.set_hand({ '9S', '9H', '2C', '5D', '3D' })
    local r = T.play({ '9S', '9H' })
    T.eq(r.chips, 10 + 9 * (1 + 2) + 9)
end)

T.test('Defibrillator: Hanging Chad forced to "+" -> first card scores 4 times', function()
    T.start_run({ jokers = { 'hanging_chad' } })
    T.select_blind()
    T.force_behavior('hanging_chad', 'plus')
    T.set_hand({ '9S', '9H', '2C', '5D', '3D' })
    local r = T.play({ '9S', '9H' })
    T.eq(r.chips, 10 + 9 * (1 + 3) + 9)
end)

T.test('Defibrillator JokerDisplay: first scored card triggers 1 + 3 = 4 times, second once', function()
    T.start_run({ jokers = { 'bplus_hanging_chad_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '9S', '9H', '4C', '5D', '2D' })
    local a, b = G.hand.cards[1], G.hand.cards[2]
    T.eq(rawget(_G, 'JokerDisplay').calculate_card_triggers(a, { a, b }, false), 1 + 3)
    T.eq(rawget(_G, 'JokerDisplay').calculate_card_triggers(b, { a, b }, false), 1)
    T.eq(T.joker_display('bplus_hanging_chad_plus').text, '')
end)

T.test('Defibrillator JokerDisplay: retrigger count follows the behaviour (vanilla 1 + 2 = 3; vanilla forced to "+" 1 + 3 = 4; "+" forced to base 1 + 2 = 3)', function()
    T.start_run({ jokers = { 'hanging_chad' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '9S', '9H', '4C', '5D', '2D' })
    local a, b = G.hand.cards[1], G.hand.cards[2]
    local JD = rawget(_G, 'JokerDisplay')
    T.eq(JD.calculate_card_triggers(a, { a, b }, false), 1 + 2)
    T.force_behavior('hanging_chad', 'plus')
    T.eq(JD.calculate_card_triggers(a, { a, b }, false), 1 + 3)
    T.eq(JD.calculate_card_triggers(b, { a, b }, false), 1)
    T.start_run({ jokers = { 'bplus_hanging_chad_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '9S', '9H', '4C', '5D', '2D' })
    a, b = G.hand.cards[1], G.hand.cards[2]
    T.force_behavior('bplus_hanging_chad_plus', 'base')
    T.eq(JD.calculate_card_triggers(a, { a, b }, false), 1 + 2)
end)
