local T = BPlus.test

T.test('Merry Joker: play a Pair -> +20 Mult (vanilla: +8 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_jolly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 + 20)
end)

T.test('Merry Joker: vanilla joker plays a Pair -> +8 Mult', function()
    T.start_run({ ante = 4, jokers = { 'jolly' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 + 8)
end)

T.test('Merry Joker: play a Full House (contains a Pair) -> +20 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_jolly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78)
    T.eq(r.mult, 4 + 20)
end)

T.test('Merry Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_jolly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Merry Joker: vanilla joker forced to "+" plays a Pair -> +20 Mult', function()
    T.start_run({ ante = 4, jokers = { 'jolly' } })
    T.force_behavior('jolly', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 + 20)
end)

T.test('Merry Joker JokerDisplay: shows +20 (Pair) with a Pair selected, +0 without; vanilla forced to "+" shows +20; "+" forced to base shows +8', function()
    T.start_run({ ante = 4, jokers = { 'bplus_jolly_plus', 'jolly' } })
    T.select_blind()
    T.set_hand({ 'KS','KH' })
    local d = T.joker_display('bplus_jolly_plus')
    T.eq(d.text, '+0')
    T.eq(d.reminder, '(Pair)')
    G.hand:unhighlight_all()
    for _, c in ipairs(G.hand.cards) do G.hand:add_to_highlighted(c, true) end
    T.eq(T.joker_display('bplus_jolly_plus').text, '+20')
    T.eq(T.joker_display('jolly').text, '+8')
    T.force_behavior('jolly', 'plus')
    T.eq(T.joker_display('jolly').text, '+20')
    T.force_behavior('bplus_jolly_plus', 'base')
    T.eq(T.joker_display('bplus_jolly_plus').text, '+8')
end)
