local T = BPlus.test

T.test('Merry Joker: play a Pair -> +20 Mult (vanilla: +8 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_jolly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 + 20)
end)

T.test('Merry Joker: vanilla joker plays a Pair -> +8 Mult', function()
    T.start_run({ ante = 4, jokers = { 'jolly' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 + 8)
end)

T.test('Merry Joker: play a Full House (contains a Pair) -> +20 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_jolly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78)
    T.eq(r.mult, 4 + 20)
end)

T.test('Merry Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_jolly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Merry Joker: vanilla joker forced to "+" plays a Pair -> +20 Mult', function()
    T.start_run({ ante = 4, jokers = { 'jolly' } })
    T.force_behavior('jolly', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2 + 20)
end)
