local T = BPlus.test

T.test('Joker+: alone, play a Pair of 2s -> +20 Mult (vanilla Joker: +4)', function()
    T.start_run({ jokers = { 'bplus_joker_plus' } })
    T.select_blind()
    T.set_hand({ '2S', '2H', '7C', '5D', '3D' })
    local r = T.play({ '2S', '2H' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 10 + 2 + 2)
    T.eq(r.mult, 2 + 20)
end)

T.test('Joker+ JokerDisplay: shows +20; vanilla Joker forced to "+" shows +20; "+" forced to base shows +4', function()
    T.start_run({ jokers = { 'bplus_joker_plus', 'joker' } })
    T.eq(T.joker_display('bplus_joker_plus').text, '+20')
    T.eq(T.joker_display('joker').text, '+4')
    T.force_behavior('joker', 'plus')
    T.eq(T.joker_display('joker').text, '+20')
    T.force_behavior('joker', nil)
    T.eq(T.joker_display('joker').text, '+4')
    T.force_behavior('bplus_joker_plus', 'base')
    T.eq(T.joker_display('bplus_joker_plus').text, '+4')
end)

T.test('Joker+ JokerDisplay: the display refreshes by itself when the behaviour changes', function()
    T.start_run({ jokers = { 'joker' } })
    T.eq(T.joker_display('joker').text, '+4')
    T.force_behavior('joker', 'plus')
    T.wait_frames(10)
    T.eq(T.joker_display('joker', true).text, '+20')
    T.force_behavior('joker', nil)
    T.wait_frames(10)
    T.eq(T.joker_display('joker', true).text, '+4')
end)
