local T = BPlus.test

T.test('Lascivious Joker: Pair of Hearts -> +5 + 5 Mult (vanilla: +3 + 3)', function()
    T.start_run({ jokers = { 'bplus_lusty_joker_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KH', 'KH', '2C', '3C', '5C' })
    local r = T.play({ 1, 2 })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 10 + 10 + 10)
    T.eq(r.mult, 2 + 5 + 5)
end)

T.test('Lascivious Joker: Pair with no Hearts -> +0 Mult', function()
    T.start_run({ jokers = { 'bplus_lusty_joker_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KC', 'KC', '2C', '3C', '5C' })
    local r = T.play({ 1, 2 })
    T.eq(r.mult, 2)
end)

T.test('Lascivious Joker: vanilla lusty_joker gives +3 + 3 Mult', function()
    T.start_run({ jokers = { 'lusty_joker' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KH', 'KH', '2C', '3C', '5C' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 3 + 3)
end)

T.test('Lascivious Joker: vanilla forced to "+" (Carpenter) gives +5 + 5 Mult', function()
    T.start_run({ jokers = { 'lusty_joker' }, ante = 3 })
    T.select_blind()
    T.force_behavior('lusty_joker', 'plus')
    T.set_hand({ 'KH', 'KH', '2C', '3C', '5C' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 5 + 5)
end)

T.test('Lascivious Joker: "+" forced to base gives +3 + 3 Mult', function()
    T.start_run({ jokers = { 'bplus_lusty_joker_plus' }, ante = 3 })
    T.select_blind()
    T.force_behavior(1, 'base')
    T.set_hand({ 'KH', 'KH', '2C', '3C', '5C' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 3 + 3)
end)

local function highlight(...)
    T.highlight({ ... })
end

T.test('Lascivious Joker JokerDisplay: "+" shows +10(Hearts); vanilla forced to "+" matches; "+" forced to base shows vanilla +6', function()
    T.start_run({ jokers = { 'bplus_lusty_joker_plus', 'lusty_joker' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KH', 'KH', '2D', '3D', '5D' })
    highlight(1, 2)
    local d = T.joker_display('bplus_lusty_joker_plus')
    T.eq(d.text, '+10')
    T.eq(d.reminder, '(Hearts)')
    local v = T.joker_display('lusty_joker')
    T.eq(v.text, '+6')
    T.eq(v.reminder, '(Hearts)')
    T.force_behavior('lusty_joker', 'plus')
    v = T.joker_display('lusty_joker')
    T.eq(v.text, '+10')
    T.eq(v.reminder, '(Hearts)')
    T.force_behavior('bplus_lusty_joker_plus', 'base')
    d = T.joker_display('bplus_lusty_joker_plus')
    T.eq(d.text, '+6')
    T.eq(d.reminder, '(Hearts)')
    T.highlight({})
end)
