local T = BPlus.test

-- Plays through Small and Big (winning them instantly) and returns at the Boss blind select screen.
local function to_boss_select()
    T.select_blind(); T.win_blind(); T.cash_out(); T.leave_shop()
    T.select_blind(); T.win_blind(); T.cash_out(); T.leave_shop()
end

T.test('El Santo: sell during a Boss Blind -> it is disabled (same as vanilla)', function()
    T.start_run({ jokers = { 'bplus_luchador_plus' }, boss = 'manacle', hands = 5, ante = 3 })
    to_boss_select()
    T.select_blind()
    T.falsy(G.GAME.blind.disabled, 'not disabled yet')
    T.sell('bplus_luchador_plus')
    T.eq(G.GAME.blind.disabled, true)
    T.falsy(G.GAME.bplus_disable_next_boss, 'no flag left over')
end)

T.test('El Santo: buy in the shop before the Boss, sell immediately -> next Boss Blind disabled when selected', function()
    T.start_run({ jokers = { 'bplus_luchador_plus' }, boss = 'manacle', hands = 5, ante = 3 })
    T.select_blind(); T.win_blind(); T.cash_out()
    T.sell('bplus_luchador_plus')
    T.eq(G.GAME.bplus_disable_next_boss, true)
    T.leave_shop()
    T.select_blind(); T.win_blind(); T.cash_out(); T.leave_shop()
    T.select_blind()
    T.wait_frames(60)
    T.eq(G.GAME.blind.disabled, true)
    T.falsy(G.GAME.bplus_disable_next_boss, 'flag cleared')
end)

T.test('El Santo: sell during the Small Blind -> the Boss Blind of that ante is disabled', function()
    T.start_run({ jokers = { 'bplus_luchador_plus' }, boss = 'manacle', hands = 5, ante = 3 })
    T.select_blind()
    T.sell('bplus_luchador_plus')
    T.falsy(G.GAME.blind.disabled, 'Small Blind itself untouched')
    T.eq(G.GAME.bplus_disable_next_boss, true)
    T.win_blind(); T.cash_out(); T.leave_shop()
    T.select_blind(); T.win_blind(); T.cash_out(); T.leave_shop()
    T.select_blind()
    T.wait_frames(60)
    T.eq(G.GAME.blind.disabled, true)
end)

T.test('El Santo: after that Boss, the following Boss is not disabled', function()
    T.start_run({ jokers = { 'bplus_luchador_plus' }, boss = 'manacle', hands = 5, ante = 3 })
    T.select_blind()
    T.sell('bplus_luchador_plus')
    T.win_blind(); T.cash_out(); T.leave_shop()
    T.select_blind(); T.win_blind(); T.cash_out(); T.leave_shop()
    T.select_blind()
    T.wait_frames(60)
    T.eq(G.GAME.blind.disabled, true, 'first boss disabled')
    T.win_blind(); T.cash_out(); T.leave_shop()
    to_boss_select()
    T.select_blind()
    T.wait_frames(60)
    T.falsy(G.GAME.blind.disabled, 'second boss active')
end)

T.test('El Santo: vanilla Luchador forced to "+" sold in the Small Blind -> Boss disabled later', function()
    T.start_run({ jokers = { 'luchador' }, boss = 'manacle', hands = 5, ante = 3 })
    T.force_behavior('luchador', 'plus')
    T.select_blind()
    T.sell('luchador')
    T.eq(G.GAME.bplus_disable_next_boss, true)
end)
