local T = BPlus.test

T.test('Livid Joker: play a Two Pair -> +24 Mult (vanilla: +10 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_mad_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', '4D', '4S' })
    T.eq(r.hand, 'Two Pair')
    T.eq(r.chips, 48)
    T.eq(r.mult, 2 + 24)
end)

T.test('Livid Joker: vanilla joker plays a Two Pair -> +10 Mult', function()
    T.start_run({ ante = 4, jokers = { 'mad' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', '4D', '4S' })
    T.eq(r.hand, 'Two Pair')
    T.eq(r.chips, 48)
    T.eq(r.mult, 2 + 10)
end)

T.test('Livid Joker: play a Full House (contains a Two Pair) -> +24 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_mad_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78)
    T.eq(r.mult, 4 + 24)
end)

T.test('Livid Joker: play a Pair -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_mad_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2)
end)

T.test('Livid Joker: vanilla joker forced to "+" plays a Two Pair -> +24 Mult', function()
    T.start_run({ ante = 4, jokers = { 'mad' } })
    T.force_behavior('mad', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', '4D', '4S' })
    T.eq(r.hand, 'Two Pair')
    T.eq(r.chips, 48)
    T.eq(r.mult, 2 + 24)
end)
