local T = BPlus.test

T.test('Todd the Odd: Aces and 7s -> +67 Chips each (vanilla: +31)', function()
    T.start_run({ jokers = { 'bplus_odd_todd_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'AS', 'AH', '7S', '7H', '9C' })
    local r = T.play({ 'AS', 'AH', '7S', '7H' })
    T.eq(r.chips, 20 + 11 + 11 + 7 + 7 + 67 * 4)
    T.eq(r.mult, 2)
end)

T.test('Todd the Odd: scoring an 8 -> no effect', function()
    T.start_run({ jokers = { 'bplus_odd_todd_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '8S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '8S' })
    T.eq(r.chips, 5 + 8)
    T.eq(r.mult, 1)
end)

T.test('Todd the Odd: vanilla forced to "+" matches (vanilla 2, "+" 2 mult)', function()
    T.start_run({ jokers = { 'odd_todd' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'AS', 'AH', '7S', '7H', '9C' })
    T.force_behavior('odd_todd', 'plus')
    local r = T.play({ 'AS', 'AH', '7S', '7H' })
    T.eq(r.chips, 20 + 11 + 11 + 7 + 7 + 67 * 4)
    T.eq(r.mult, 2)
end)

T.test('Todd the Odd: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'odd_todd' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'AS', 'AH', '7S', '7H', '9C' })
    local r = T.play({ 'AS', 'AH', '7S', '7H' })
    T.eq(r.chips, 20 + 11 + 11 + 7 + 7 + 31 * 4)
    T.eq(r.mult, 2)
end)
