local T = BPlus.test

T.test('The New Order: play a Straight -> X4 Mult (vanilla: X3 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_order_plus' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 * 4)
end)

T.test('The New Order: vanilla joker plays a Straight -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'order' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 * 3)
end)

T.test('The New Order: play a Straight Flush (contains a Straight) -> X4 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_order_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135)
    T.eq(r.mult, 8 * 4)
end)

T.test('The New Order: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_order_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('The New Order: vanilla joker forced to "+" plays a Straight -> X4 Mult', function()
    T.start_run({ ante = 4, jokers = { 'order' } })
    T.force_behavior('order', 'plus')
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 * 4)
end)
