local T = BPlus.test

T.test('The New Order: play a Straight -> X4 Mult (vanilla: X3 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_order_plus' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 * 4)
end)

T.test('The New Order: vanilla joker plays a Straight -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'order' } })
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 * 3)
end)

T.test('The New Order: play a Straight Flush (contains a Straight) -> X4 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_order_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135)
    T.eq(r.mult, 8 * 4)
end)

T.test('The New Order: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_order_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('The New Order: vanilla joker forced to "+" plays a Straight -> X4 Mult', function()
    T.start_run({ ante = 4, jokers = { 'order' } })
    T.force_behavior('order', 'plus')
    T.select_blind()
    T.set_hand({ '5S', '6H', '7C', '8D', '9S' })
    local r = T.play({ '5S', '6H', '7C', '8D', '9S' })
    T.eq(r.hand, 'Straight')
    T.eq(r.chips, 65)
    T.eq(r.mult, 4 * 4)
end)

T.test('The New Order JokerDisplay: shows X4 (Straight) with a Straight selected, X1 without; vanilla forced to "+" shows X4; "+" forced to base shows X3', function()
    T.start_run({ ante = 4, jokers = { 'bplus_order_plus', 'order' } })
    T.select_blind()
    T.set_hand({ '5S','6H','7C','8D','9S' })
    local d = T.joker_display('bplus_order_plus')
    T.eq(d.text, 'X1')
    T.eq(d.reminder, '(Straight)')
    G.hand:unhighlight_all()
    for _, c in ipairs(G.hand.cards) do G.hand:add_to_highlighted(c, true) end
    T.eq(T.joker_display('bplus_order_plus').text, 'X4')
    T.eq(T.joker_display('order').text, 'X3')
    T.force_behavior('order', 'plus')
    T.eq(T.joker_display('order').text, 'X4')
    T.force_behavior('bplus_order_plus', 'base')
    T.eq(T.joker_display('bplus_order_plus').text, 'X3')
end)
