local T = BPlus.test

T.test('Selfie: Pair of Kings -> only the first King gives X4 (vanilla: X2)', function()
    T.start_run({ jokers = { 'bplus_photograph_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '9C', '6D', '3H' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.chips, 10 + 10 + 10)
    T.eq(r.mult, 2 * 4)
end)

T.test('Selfie: no face cards scored -> no effect', function()
    T.start_run({ jokers = { 'bplus_photograph_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '2S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '2S' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1)
end)

T.test('Selfie: vanilla forced to "+" matches (vanilla 2 * 2, "+" 2 * 4 mult)', function()
    T.start_run({ jokers = { 'photograph' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '9C', '6D', '3H' })
    T.force_behavior('photograph', 'plus')
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.chips, 10 + 10 + 10)
    T.eq(r.mult, 2 * 4)
end)

T.test('Selfie: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'photograph' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '9C', '6D', '3H' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.chips, 10 + 10 + 10)
    T.eq(r.mult, 2 * 2)
end)
