local T = BPlus.test

T.test('Tonkotsu: discard 5 cards -> X3 - 5 * 0.01 = X2.95', function()
    T.start_run({ jokers = { 'bplus_ramen_plus' }, hands = 5, discards = 5, ante = 3 })
    T.select_blind()
    T.set_hand({ '2S', '3H', '7C', '5D', '9D', 'KD' })
    T.discard({ '2S', '3H', '7C', '5D', '9D' })
    T.near(T.joker(1).ability.extra.Xmult, 3 - 5 * 0.01, 1e-6)
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    local r = T.play({ '2S' })
    T.near(r.mult, 1 * (3 - 5 * 0.01), 1e-6)
end)

T.test('Tonkotsu: destroyed after 200 discarded cards ((3 - 1) / 0.01 = 200)', function()
    T.start_run({ jokers = { 'bplus_ramen_plus' }, hands = 5, discards = 5, ante = 3 })
    T.select_blind()
    local c = T.joker(1)
    T.near((c.ability.extra.Xmult - 1) / c.ability.extra.Xmult_mod, 200, 1e-6)
    c.ability.extra.Xmult = 1.03   -- as if 197 cards were discarded
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.discard({ '2S', '3H' })
    T.truthy(T.joker(1), 'still alive after 2 more')
    T.discard({ '7C', '5D' })
    T.falsy(T.joker(1), 'eaten on the 200th card')
end)

T.test('Tonkotsu: Ramen partly used up, upgrade -> starts fresh at X3', function()
    T.start_run({ jokers = { 'ramen' }, hands = 5, discards = 5, ante = 3 })
    T.select_blind()
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.discard({ '2S', '3H', '7C' })
    T.near(T.joker(1).ability.x_mult, 2 - 3 * 0.01, 1e-6, 'vanilla value')
    local card = T.upgrade('ramen')
    T.eq(card.ability.extra.Xmult, 3, 'reset')
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.near(T.play({ '2S' }).mult, 1 * 3, 1e-6)
end)

T.test('Tonkotsu JokerDisplay: X3 at start, X2.95 after discarding 5 cards', function()
    T.start_run({ jokers = { 'bplus_ramen_plus' }, hands = 5, discards = 5, ante = 3 })
    T.select_blind()
    T.eq(T.joker_display('bplus_ramen_plus').text, 'X3')
    T.set_hand({ '2S', '3H', '7C', '5D', '9D', 'KD' })
    T.discard({ '2S', '3H', '7C', '5D', '9D' })
    T.eq(T.joker_display('bplus_ramen_plus').text, 'X2.95')
end)
