local T = BPlus.test

-- Open the first booster in the shop and skip it.
local function skip_a_pack()
    T.buy(G.shop_booster.cards[1].config.center.key)
    T.skip_pack()
end

T.test('Crimson Card: skip 2 Booster Packs -> +5 + 5 = 10 Mult (vanilla: 3 + 3)', function()
    T.start_run({ jokers = { 'bplus_red_card_plus' }, dollars = 100, ante = 3 })
    T.to_shop()
    skip_a_pack()
    T.eq(T.joker(1).ability.extra.mult, 5)
    skip_a_pack()
    T.eq(T.joker(1).ability.extra.mult, 5 + 5)
    T.leave_shop()
    T.select_blind()
    T.eq(T.play({ 1 }).mult, 1 + 10)
end)

T.test('Crimson Card: vanilla Red Card gains +3 per skipped pack', function()
    T.start_run({ jokers = { 'red_card' }, dollars = 100, ante = 3 })
    T.to_shop()
    skip_a_pack()
    skip_a_pack()
    T.eq(T.joker(1).ability.mult, 3 + 3)
end)

T.test("Crimson Card: Red Card at +6 Mult, upgrade -> keeps +6 Mult, later gains use the '+' rate", function()
    T.start_run({ jokers = { { key = 'red_card', edition = 'foil' } }, dollars = 100, ante = 3 })
    T.to_shop()
    skip_a_pack()
    skip_a_pack()
    T.eq(T.joker(1).ability.mult, 6, 'vanilla value')
    local card = T.upgrade('red_card')
    T.eq(card.ability.extra.mult, 6, 'carried over')
    T.truthy(card.edition and card.edition.foil, 'foil kept')
    T.leave_shop()
    T.to_shop()
    skip_a_pack()
    T.eq(card.ability.extra.mult, 6 + 5)
end)

T.test('Crimson Card: vanilla Red Card forced to "+" gains +5 and keeps its stored value', function()
    T.start_run({ jokers = { 'red_card' }, dollars = 100, ante = 3 })
    T.to_shop()
    skip_a_pack()
    T.force_behavior('red_card', 'plus')
    skip_a_pack()
    T.eq(T.joker(1).ability.mult, 3 + 5)
end)

T.test('Crimson Card: forced to base gains +3 and keeps its value', function()
    T.start_run({ jokers = { 'bplus_red_card_plus' }, dollars = 100, ante = 3 })
    T.to_shop()
    skip_a_pack()
    T.force_behavior(1, 'base')
    skip_a_pack()
    T.eq(T.joker(1).ability.extra.mult, 5 + 3)
end)

T.test('Crimson Card JokerDisplay: 2 skips -> +10 ("+") vs +6 (vanilla); stored values kept when forced to "+" / base', function()
    T.start_run({ jokers = { 'bplus_red_card_plus', 'red_card' }, dollars = 100, ante = 3 })
    T.to_shop()
    skip_a_pack()
    skip_a_pack()
    T.eq(T.joker_display('bplus_red_card_plus').text, '+' .. (5 + 5))
    T.eq(T.joker_display('red_card').text, '+' .. (3 + 3))
    T.force_behavior('red_card', 'plus')
    T.eq(T.joker_display('red_card').text, '+' .. (3 + 3))
    T.force_behavior('bplus_red_card_plus', 'base')
    T.eq(T.joker_display('bplus_red_card_plus').text, '+' .. (5 + 5))
end)
