local T = BPlus.test

local function no_face()
    T.set_hand({ '2S', '2H', '7C', '5D', '3D' })
    return T.play({ '2S', '2H' })
end

local function with_face()
    T.set_hand({ 'KS', 'KH', '7C', '5D', '3D' })
    return T.play({ 'KS', 'KH' })
end

T.test('Express Bus: 3 hands without face cards -> +2 + 2 + 2 = 6 Mult', function()
    T.start_run({ jokers = { 'bplus_ride_the_bus_plus' }, hands = 5 })
    T.select_blind()
    T.eq(no_face().mult, 2 + 2)
    T.eq(no_face().mult, 2 + 2 + 2)
    T.eq(no_face().mult, 2 + 2 + 2 + 2)
    T.eq(T.joker(1).ability.extra.mult, 2 + 2 + 2)
end)

T.test('Express Bus: then a hand with a scoring face card -> Mult resets to 0', function()
    T.start_run({ jokers = { 'bplus_ride_the_bus_plus' }, hands = 5 })
    T.select_blind()
    no_face(); no_face(); no_face()
    T.eq(with_face().mult, 2)
    T.eq(T.joker(1).ability.extra.mult, 0)
end)

T.test("Express Bus: Ride the Bus at +3 Mult, upgrade -> keeps +3, later gains use the '+' rate", function()
    T.start_run({ jokers = { { key = 'ride_the_bus', edition = 'holo' } }, hands = 6, ante = 3 })
    T.select_blind()
    no_face(); no_face(); no_face()
    T.eq(T.joker(1).ability.mult, 1 + 1 + 1, 'vanilla value')
    local card = T.upgrade('ride_the_bus')
    T.eq(card.ability.extra.mult, 1 + 1 + 1, 'carried over')
    T.truthy(card.edition and card.edition.holo, 'holo kept')
    local r = no_face()
    T.eq(card.ability.extra.mult, 3 + 2)
    T.eq(r.mult, (2 + 3 + 2 + 10) * 1)   -- base 2 + bus 5 + holo 10
end)

T.test('Express Bus: Ride the Bus forced to "+" keeps its stored value, only the rate changes', function()
    T.start_run({ jokers = { 'ride_the_bus' }, hands = 6 })
    T.select_blind()
    no_face()
    T.eq(T.joker(1).ability.mult, 1)
    T.force_behavior('ride_the_bus', 'plus')
    T.eq(no_face().mult, 2 + 1 + 2)
    T.eq(T.joker(1).ability.mult, 1 + 2, 'stored on the vanilla card')
    T.force_behavior('ride_the_bus', nil)
    T.eq(no_face().mult, 2 + 3 + 1)
end)

T.test('Express Bus: forced to base gains +1 per hand and keeps its value', function()
    T.start_run({ jokers = { 'bplus_ride_the_bus_plus' }, hands = 6 })
    T.select_blind()
    no_face()
    T.force_behavior(1, 'base')
    T.eq(no_face().mult, 2 + 2 + 1)
    T.eq(T.joker(1).ability.extra.mult, 2 + 1)
    T.force_behavior(1, nil)
    T.eq(no_face().mult, 2 + 3 + 2)
end)

T.test('Express Bus JokerDisplay: +0 -> after 2 hands +4; forced behaviours keep the stored mult', function()
    T.start_run({ jokers = { 'bplus_ride_the_bus_plus', 'ride_the_bus' }, hands = 5, ante = 3 })
    T.select_blind()
    T.eq(T.joker_display('bplus_ride_the_bus_plus').text, '+0')
    no_face(); no_face()
    T.eq(T.joker_display('bplus_ride_the_bus_plus').text, '+' .. (2 + 2))
    T.eq(T.joker_display('ride_the_bus').text, '+' .. (1 + 1))
    T.force_behavior('ride_the_bus', 'plus')
    T.eq(T.joker_display('ride_the_bus').text, '+' .. (1 + 1)) -- stored value kept, shown through the "+" definition
    T.force_behavior('bplus_ride_the_bus_plus', 'base')
    T.eq(T.joker_display('bplus_ride_the_bus_plus').text, '+' .. (2 + 2)) -- stored value kept, vanilla definition
end)
