local T = BPlus.test

local function pair()
    T.set_hand({ 'KD', 'KD', '2C', '3C', '5C' })
    return T.play({ 1, 2 })
end

T.test('Gemstone: Pair of Diamonds -> +$2 + $2 (vanilla: +$1 + $1)', function()
    T.start_run({ jokers = { 'bplus_rough_gem_plus' }, ante = 3 })
    T.select_blind()
    T.eq(pair().dollars, 2 + 2)
end)

T.test('Gemstone: vanilla Rough Gem gives +$1 + $1', function()
    T.start_run({ jokers = { 'rough_gem' }, ante = 3 })
    T.select_blind()
    T.eq(pair().dollars, 1 + 1)
end)

T.test('Gemstone: vanilla forced to "+" gives +$2 + $2', function()
    T.start_run({ jokers = { 'rough_gem' }, ante = 3 })
    T.select_blind()
    T.force_behavior('rough_gem', 'plus')
    T.eq(pair().dollars, 2 + 2)
end)

local function highlight(...)
    T.highlight({ ... })
end

T.test('Gemstone JokerDisplay: "+" shows +$4(Diamonds); vanilla forced to "+" matches; "+" forced to base shows vanilla +$2', function()
    T.start_run({ jokers = { 'bplus_rough_gem_plus', 'rough_gem' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KD', 'KD', '2C', '3C', '5C' })
    highlight(1, 2)
    local d = T.joker_display('bplus_rough_gem_plus')
    T.eq(d.text, '+$4')
    T.eq(d.reminder, '(Diamonds)')
    local v = T.joker_display('rough_gem')
    T.eq(v.text, '+$2')
    T.eq(v.reminder, '(Diamonds)')
    T.force_behavior('rough_gem', 'plus')
    v = T.joker_display('rough_gem')
    T.eq(v.text, '+$4')
    T.eq(v.reminder, '(Diamonds)')
    T.force_behavior('bplus_rough_gem_plus', 'base')
    d = T.joker_display('bplus_rough_gem_plus')
    T.eq(d.text, '+$2')
    T.eq(d.reminder, '(Diamonds)')
    T.highlight({})
end)
