local T = BPlus.test

local function jd_select(specs)
    T.highlight(specs)
end

T.test('Nightmare: 2 face cards -> +60 + 60 Chips (vanilla: +30 + 30)', function()
    T.start_run({ jokers = { 'bplus_scary_face_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '9C', '6D', '3H' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.chips, 10 + 10 + 10 + 60 + 60)
    T.eq(r.mult, 2)
end)

T.test('Nightmare: scoring a 7 -> no effect', function()
    T.start_run({ jokers = { 'bplus_scary_face_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '7S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '7S' })
    T.eq(r.chips, 5 + 7)
    T.eq(r.mult, 1)
end)

T.test('Nightmare: Pareidolia makes every card a face card', function()
    T.start_run({ jokers = { 'bplus_scary_face_plus', 'pareidolia' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '7S', '7H', '9C', '6D', '3H' })
    local r = T.play({ '7S', '7H' })
    T.eq(r.chips, 10 + 7 + 7 + 60 + 60)
end)

T.test('Nightmare: vanilla forced to "+" matches (vanilla 2, "+" 2 mult)', function()
    T.start_run({ jokers = { 'scary_face' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '9C', '6D', '3H' })
    T.force_behavior('scary_face', 'plus')
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.chips, 10 + 10 + 10 + 60 + 60)
    T.eq(r.mult, 2)
end)

T.test('Nightmare: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'scary_face' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '9C', '6D', '3H' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.chips, 10 + 10 + 10 + 30 + 30)
    T.eq(r.mult, 2)
end)

T.test('Nightmare JokerDisplay: "+" shows the "+" numbers; vanilla forced to "+" shows them too; "+" forced to base shows vanilla numbers', function()
    T.start_run({ ante = 4, jokers = { 'bplus_scary_face_plus', 'scary_face' } })
    T.select_blind()
    T.set_hand({ 'KS','KH','2D','3C','5H' })
    jd_select({ 'KS','KH' })
    local d = T.joker_display('bplus_scary_face_plus')
    T.eq(d.text, '+' .. (60 * 2))
    T.eq(d.reminder, '(Face Cards)')
    T.eq(T.joker_display('scary_face').text, '+' .. (30 * 2))
    T.force_behavior('scary_face', 'plus')
    T.eq(T.joker_display('scary_face').text, '+' .. (60 * 2))
    T.force_behavior('bplus_scary_face_plus', 'base')
    T.eq(T.joker_display('bplus_scary_face_plus').text, '+' .. (30 * 2))
end)
