local T = BPlus.test

T.test('Moonshot: holding 2 Queens -> +21 + 21 Mult (vanilla: +13 + 13)', function()
    T.start_run({ jokers = { 'bplus_shoot_the_moon_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'QS', 'QH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 + 21 + 21)
end)

T.test('Moonshot: holding no Queens -> no effect', function()
    T.start_run({ jokers = { 'bplus_shoot_the_moon_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1)
end)

T.test('Moonshot: vanilla forced to "+" matches (vanilla 1 + 13 + 13, "+" 1 + 21 + 21 mult)', function()
    T.start_run({ jokers = { 'shoot_the_moon' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'QS', 'QH', '2C', '9C', '6D' })
    T.force_behavior('shoot_the_moon', 'plus')
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 + 21 + 21)
end)

T.test('Moonshot: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'shoot_the_moon' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'QS', 'QH', '2C', '9C', '6D' })
    local r = T.play({ '2C' })
    T.eq(r.chips, 5 + 2)
    T.eq(r.mult, 1 + 13 + 13)
end)
