local T = BPlus.test

T.test('Foxy Joker: play a Pair -> +100 Chips (vanilla: +50 Chips)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_sly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30 + 100)
    T.eq(r.mult, 2)
end)

T.test('Foxy Joker: vanilla joker plays a Pair -> +50 Chips', function()
    T.start_run({ ante = 4, jokers = { 'sly' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30 + 50)
    T.eq(r.mult, 2)
end)

T.test('Foxy Joker: play a Full House (contains a Pair) -> +100 Chips', function()
    T.start_run({ ante = 4, jokers = { 'bplus_sly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78 + 100)
    T.eq(r.mult, 4)
end)

T.test('Foxy Joker: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_sly_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('Foxy Joker: vanilla joker forced to "+" plays a Pair -> +100 Chips', function()
    T.start_run({ ante = 4, jokers = { 'sly' } })
    T.force_behavior('sly', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30 + 100)
    T.eq(r.mult, 2)
end)

T.test('Foxy Joker JokerDisplay: shows +100 (Pair) with a Pair selected, +0 without; vanilla forced to "+" shows +100; "+" forced to base shows +50', function()
    T.start_run({ ante = 4, jokers = { 'bplus_sly_plus', 'sly' } })
    T.select_blind()
    T.set_hand({ 'KS','KH' })
    local d = T.joker_display('bplus_sly_plus')
    T.eq(d.text, '+0')
    T.eq(d.reminder, '(Pair)')
    T.highlight({ 1, 2 })
    T.eq(T.joker_display('bplus_sly_plus').text, '+100')
    T.eq(T.joker_display('sly').text, '+50')
    T.force_behavior('sly', 'plus')
    T.eq(T.joker_display('sly').text, '+100')
    T.force_behavior('bplus_sly_plus', 'base')
    T.eq(T.joker_display('bplus_sly_plus').text, '+50')
end)
