local T = BPlus.test

T.test('Monolith: 3 Stone cards in deck -> +50 * 3 Chips', function()
    T.start_run({ jokers = { 'bplus_stone_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ { '2S', enhancement = 'stone' }, { '3S', enhancement = 'stone' }, { '4S', enhancement = 'stone' }, 'AH', '6D' })
    local r = T.play({ 'AH' })
    T.eq(r.chips, 5 + 11 + 50 * 3)
    T.eq(r.mult, 1)
end)

T.test('Monolith: no Stone cards -> no effect', function()
    T.start_run({ jokers = { 'bplus_stone_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'AH', '6D', '7C', '8C', '9D' })
    local r = T.play({ 'AH' })
    T.eq(r.chips, 5 + 11)
    T.eq(r.mult, 1)
end)

T.test('Monolith: vanilla forced to "+" -> +50 * 3', function()
    T.start_run({ jokers = { 'stone' }, ante = 3 })
    T.select_blind()
    T.force_behavior('stone', 'plus')
    T.set_hand({ { '2S', enhancement = 'stone' }, { '3S', enhancement = 'stone' }, { '4S', enhancement = 'stone' }, 'AH', '6D' })
    local r = T.play({ 'AH' })
    T.eq(r.chips, 5 + 11 + 50 * 3)
    T.eq(r.mult, 1)
end)

T.test('Monolith: vanilla Stone Joker -> +25 * 3', function()
    T.start_run({ jokers = { 'stone' }, ante = 3 })
    T.select_blind()
    T.set_hand({ { '2S', enhancement = 'stone' }, { '3S', enhancement = 'stone' }, { '4S', enhancement = 'stone' }, 'AH', '6D' })
    local r = T.play({ 'AH' })
    T.eq(r.chips, 5 + 11 + 25 * 3)
    T.eq(r.mult, 1)
end)
