local T = BPlus.test

local function hand_size() return G.hand.config.card_limit end

T.test('Daredevil: play any hand -> +350 Chips (vanilla: +250)', function()
    T.start_run({ jokers = { 'bplus_stuntman_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 350)
    T.eq(r.mult, 1)
end)

T.test('Daredevil: hand size is 8 - 1 = 7 (vanilla: 8 - 2 = 6)', function()
    T.start_run({ jokers = { 'bplus_stuntman_plus' } })
    T.eq(hand_size(), 8 - 1)
end)

T.test('Daredevil: sell it -> hand size back to 8', function()
    T.start_run({ jokers = { 'bplus_stuntman_plus' } })
    T.sell('bplus_stuntman_plus')
    T.eq(hand_size(), 8)
end)

T.test('Daredevil: upgrade Stuntman -> hand size goes from 6 to 7', function()
    T.start_run({ jokers = { 'stuntman' } })
    T.eq(hand_size(), 8 - 2)
    T.upgrade('stuntman')
    T.eq(hand_size(), 8 - 1)
end)

T.test('Daredevil: Stuntman forced to "+" -> 350 Chips and hand size 7; back -> 250 and 6', function()
    T.start_run({ jokers = { 'stuntman' }, ante = 3 })
    T.select_blind()
    T.eq(hand_size(), 8 - 2)
    T.force_behavior('stuntman', 'plus')
    T.eq(hand_size(), 8 - 1)
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 350)
    T.force_behavior('stuntman', nil)
    T.eq(hand_size(), 8 - 2)
end)

T.test('Daredevil: Stuntman forced to "+", then sold -> hand size back to 8', function()
    T.start_run({ jokers = { 'stuntman' } })
    T.force_behavior('stuntman', 'plus')
    T.sell('stuntman')
    T.eq(hand_size(), 8)
end)

T.test('Daredevil: forced to base -> 250 Chips and hand size 6', function()
    T.start_run({ jokers = { 'bplus_stuntman_plus' }, ante = 3 })
    T.select_blind()
    T.force_behavior(1, 'base')
    T.eq(hand_size(), 8 - 2)
    T.set_hand({ 'AS', '9C', '6D', '3H', '2S' })
    local r = T.play({ 'AS' })
    T.eq(r.chips, 5 + 11 + 250)
end)

T.test('Daredevil JokerDisplay: "+" shows the "+" numbers; vanilla forced to "+" shows them too; "+" forced to base shows vanilla numbers', function()
    T.start_run({ ante = 4, jokers = { 'bplus_stuntman_plus', 'stuntman' } })
    T.select_blind()
    local d = T.joker_display('bplus_stuntman_plus')
    T.eq(d.text, '+350')
    T.eq(T.joker_display('stuntman').text, '+250')
    T.force_behavior('stuntman', 'plus')
    T.eq(T.joker_display('stuntman').text, '+350')
    T.force_behavior('bplus_stuntman_plus', 'base')
    T.eq(T.joker_display('bplus_stuntman_plus').text, '+250')
end)
