local T = BPlus.test

T.test('Buccaneer: with Joker (sell $1) and Golden Joker (sell $3) -> +2 * (1 + 3) = 8 Mult', function()
    T.start_run({ jokers = { 'bplus_swashbuckler_plus', 'joker', 'golden' }, hands = 5, ante = 3 })
    T.select_blind()
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.eq(T.play({ '2S' }).mult, 1 + 4 + 2 * (1 + 3))   -- base 1, Joker +4, Buccaneer
end)

T.test('Buccaneer: alone -> +0 Mult', function()
    T.start_run({ jokers = { 'bplus_swashbuckler_plus' }, hands = 5, ante = 3 })
    T.select_blind()
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.eq(T.play({ '2S' }).mult, 1 + 0)
end)

T.test('Buccaneer: Swashbuckler forced to "+" doubles, forced "base" on the "+" joker halves again', function()
    T.start_run({ jokers = { 'swashbuckler', 'golden' }, hands = 5, ante = 3 })
    T.select_blind()
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.eq(T.play({ '2S' }).mult, 1 + 3)
    T.force_behavior('swashbuckler', 'plus')
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.eq(T.play({ '2S' }).mult, 1 + 2 * 3)
end)

T.test('Buccaneer: "+" joker forced to "base" behaves as vanilla Swashbuckler', function()
    T.start_run({ jokers = { 'bplus_swashbuckler_plus', 'golden' }, hands = 5, ante = 3 })
    T.force_behavior(1, 'base')
    T.select_blind()
    T.wait_frames(5)
    T.set_hand({ '2S', '3H', '7C', '5D', '9D' })
    T.eq(T.play({ '2S' }).mult, 1 + 3)
end)

T.test('Buccaneer JokerDisplay: others sell for $2 + $1 + $3 -> +12; vanilla forced to "+" shows +12; "+" forced to base shows vanilla +6', function()
    T.start_run({ jokers = { 'bplus_swashbuckler_plus', 'swashbuckler', 'joker', 'golden' }, hands = 5, ante = 3 })
    local others = T.joker(2).sell_cost + 1 + 3 -- vanilla Swashbuckler (sell $2), Joker ($1), Golden Joker ($3)
    T.eq(others, 2 + 1 + 3)
    T.eq(T.joker_display('bplus_swashbuckler_plus').text, '+' .. 2 * (2 + 1 + 3))
    T.force_behavior('swashbuckler', 'plus')
    T.eq(T.joker_display('swashbuckler').text, '+' .. (2 * (T.joker(1).sell_cost + 1 + 3)))
    T.force_behavior('bplus_swashbuckler_plus', 'base')
    T.wait_frames(5) -- vanilla recomputes ability.mult in Card:update
    T.eq(T.joker_display('bplus_swashbuckler_plus').text, '+' .. (2 + 1 + 3))
end)
