local T = BPlus.test

local GOLD = { { 'KH', enhancement = 'gold' }, { 'KS', enhancement = 'gold' }, '9D', '5C', '2D' }

T.test('Goldbars: score 2 Gold cards -> +$5 + $5 (vanilla: +$4 + $4)', function()
    T.start_run({ dollars = 0, ante = 3, jokers = { 'bplus_ticket_plus' } })
    T.select_blind()
    T.set_hand(GOLD)
    T.eq(T.play({ 'KH', 'KS' }).dollars, 5 + 5)
end)

T.test('Goldbars: vanilla Golden Ticket pays $4 + $4', function()
    T.start_run({ dollars = 0, ante = 3, jokers = { 'ticket' } })
    T.select_blind()
    T.set_hand(GOLD)
    T.eq(T.play({ 'KH', 'KS' }).dollars, 4 + 4)
end)

T.test('Goldbars: non-Gold cards earn nothing', function()
    T.start_run({ dollars = 0, ante = 3, jokers = { 'bplus_ticket_plus' } })
    T.select_blind()
    T.set_hand(GOLD)
    T.eq(T.play({ '9D', '5C' }).dollars, 0)
end)

T.test('Goldbars: Golden Ticket forced to "+" pays $5 + $5', function()
    T.start_run({ dollars = 0, ante = 3, jokers = { 'ticket' } })
    T.force_behavior('ticket', 'plus')
    T.select_blind()
    T.set_hand(GOLD)
    T.eq(T.play({ 'KH', 'KS' }).dollars, 5 + 5)
end)

T.test('Goldbars JokerDisplay: 2 Gold cards selected -> +$10 (Gold); vanilla forced to "+" +$10; "+" forced to base +$8', function()
    T.start_run({ jokers = { 'bplus_ticket_plus', 'ticket' }, ante = 3 })
    T.select_blind()
    T.set_hand({ { 'KH', enhancement = 'gold' }, { 'KS', enhancement = 'gold' }, '9D', '5C', '2D', '3C', '4C', '7C' })
    T.highlight({ 'KH', 'KS' })
    local d = T.joker_display('bplus_ticket_plus')
    T.eq(d.text, '+$' .. (5 + 5))
    T.eq(d.reminder, '(Gold)')
    T.eq(T.joker_display('ticket').text, '+$' .. (4 + 4))
    T.force_behavior('ticket', 'plus')
    T.eq(T.joker_display('ticket').text, '+$' .. (5 + 5))
    T.force_behavior('bplus_ticket_plus', 'base')
    T.eq(T.joker_display('bplus_ticket_plus').text, '+$' .. (4 + 4))
    T.highlight({})
end)
