local T = BPlus.test

T.test('To the Stars: end round with $25 -> interest (1 + 2) * 5 = $15 (vanilla: (1 + 1) * 5 = $10)', function()
    T.start_run({ dollars = 25, jokers = { 'bplus_to_the_moon_plus' } })
    T.select_blind()
    T.win_blind()
    T.eq(T.cash_out(), 3 + 4 + (1 + 2) * 5)
end)

T.test('To the Stars: vanilla To the Moon pays (1 + 1) * 5', function()
    T.start_run({ dollars = 25, jokers = { 'to_the_moon' } })
    T.select_blind()
    T.win_blind()
    T.eq(T.cash_out(), 3 + 4 + (1 + 1) * 5)
end)

T.test('To the Stars: sell it -> interest back to $1 per $5', function()
    T.start_run({ jokers = { 'bplus_to_the_moon_plus' } })
    T.eq(G.GAME.interest_amount, 1 + 2)
    T.sell('bplus_to_the_moon_plus')
    T.eq(G.GAME.interest_amount, 1)
end)

T.test('To the Stars: upgrade To the Moon -> interest 1 + 2, not 1 + 1 + 2', function()
    T.start_run({ jokers = { 'to_the_moon' } })
    T.eq(G.GAME.interest_amount, 1 + 1)
    T.upgrade('to_the_moon')
    T.eq(G.GAME.interest_amount, 1 + 2)
end)

T.test('To the Stars: To the Moon forced to "+", back to base, sold while "+"', function()
    T.start_run({ jokers = { 'to_the_moon' } })
    T.force_behavior('to_the_moon', 'plus')
    T.eq(G.GAME.interest_amount, 1 + 2)
    T.force_behavior('to_the_moon', nil)
    T.eq(G.GAME.interest_amount, 1 + 1)
    T.force_behavior('to_the_moon', 'plus')
    T.sell('to_the_moon')
    T.eq(G.GAME.interest_amount, 1)
end)
