local T = BPlus.test

T.test('Bee Gees Joker: play a Three of a Kind -> X4 Mult (vanilla: X3 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_trio_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 * 4)
end)

T.test('Bee Gees Joker: vanilla joker plays a Three of a Kind -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'trio' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 * 3)
end)

T.test('Bee Gees Joker: play a Full House (contains a Three of a Kind) -> X4 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_trio_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78)
    T.eq(r.mult, 4 * 4)
end)

T.test('Bee Gees Joker: play a Pair -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_trio_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2)
end)

T.test('Bee Gees Joker: vanilla joker forced to "+" plays a Three of a Kind -> X4 Mult', function()
    T.start_run({ ante = 4, jokers = { 'trio' } })
    T.force_behavior('trio', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 * 4)
end)
