local T = BPlus.test

local HAND = { 'KS', 'QH', '7D', '2C', '3C', '4C', '5C', '6C' }

T.test('Chase Card: first discard is 1 card -> card destroyed, +$6 (vanilla: +$3)', function()
    T.start_run({ dollars = 0, jokers = { 'bplus_trading_plus' } })
    T.select_blind()
    T.set_hand(HAND)
    local before = #G.playing_cards
    T.discard({ 'KS' })
    T.eq(G.GAME.dollars, 6)
    T.eq(#G.playing_cards, before - 1)
end)

T.test('Chase Card: vanilla Trading Card pays $3', function()
    T.start_run({ dollars = 0, jokers = { 'trading' } })
    T.select_blind()
    T.set_hand(HAND)
    T.discard({ 'KS' })
    T.eq(G.GAME.dollars, 3)
end)

T.test('Chase Card: first discard is 2 cards -> nothing', function()
    T.start_run({ dollars = 0, jokers = { 'bplus_trading_plus' } })
    T.select_blind()
    T.set_hand(HAND)
    local before = #G.playing_cards
    T.discard({ 'KS', 'QH' })
    T.eq(G.GAME.dollars, 0)
    T.eq(#G.playing_cards, before)
end)

T.test('Chase Card: second discard of 1 card -> nothing', function()
    T.start_run({ dollars = 0, jokers = { 'bplus_trading_plus' } })
    T.select_blind()
    T.set_hand(HAND)
    T.discard({ 'KS', 'QH' })
    T.discard({ 1 })
    T.eq(G.GAME.dollars, 0)
end)

T.test('Chase Card: Trading Card forced to "+" pays $6', function()
    T.start_run({ dollars = 0, jokers = { 'trading' } })
    T.force_behavior('trading', 'plus')
    T.select_blind()
    T.set_hand(HAND)
    T.discard({ 'KS' })
    T.eq(G.GAME.dollars, 6)
end)

T.test('Chase Card JokerDisplay: 1 card selected on first discard -> +$6 (Active); vanilla forced to "+" +$6; "+" forced to base +$3', function()
    T.start_run({ jokers = { 'bplus_trading_plus', 'trading' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', '9D', '5C', '2D', '3C', '4C', '7C' })
    for _, c in ipairs(T.hand_cards({ 'KS' })) do G.hand:add_to_highlighted(c, true) end
    local d = T.joker_display('bplus_trading_plus')
    T.eq(d.text, '+$6')
    T.eq(d.reminder, '(Active!)')
    T.eq(T.joker_display('trading').text, '+$3')
    T.force_behavior('trading', 'plus')
    T.eq(T.joker_display('trading').text, '+$6')
    T.force_behavior('bplus_trading_plus', 'base')
    T.eq(T.joker_display('bplus_trading_plus').text, '+$3')
    G.hand:unhighlight_all()
end)
