local T = BPlus.test

T.test('The Nation: play a Flush -> X3 Mult (vanilla: X2 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_tribe_plus' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 * 3)
end)

T.test('The Nation: vanilla joker plays a Flush -> X2 Mult', function()
    T.start_run({ ante = 4, jokers = { 'tribe' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 * 2)
end)

T.test('The Nation: play a Straight Flush (contains a Flush) -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_tribe_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135)
    T.eq(r.mult, 8 * 3)
end)

T.test('The Nation: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_tribe_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('The Nation: vanilla joker forced to "+" plays a Flush -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'tribe' } })
    T.force_behavior('tribe', 'plus')
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 * 3)
end)
