local T = BPlus.test

T.test('Triboulet+: score a Jack -> X2 (vanilla: nothing)', function()
    T.start_run({ jokers = { 'bplus_triboulet_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'JS', '7H', '5C', '3D', '2D' })
    local r = T.play({ 'JS' })
    T.eq(r.chips, 5 + 10)
    T.eq(r.mult, 1 * 2)
end)

T.test('Triboulet+: score Kings and Queens -> X2 each (2 * 2 * 2 * 2 * 2)', function()
    T.start_run({ jokers = { 'bplus_triboulet_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'QS', 'QH', '3D' })
    local r = T.play({ 'KS', 'KH', 'QS', 'QH' })
    T.eq(r.hand, 'Two Pair')
    T.eq(r.chips, 20 + 10 * 4)
    T.eq(r.mult, 2 * 2 * 2 * 2 * 2)
end)

T.test('Triboulet+: score a 10 -> nothing', function()
    T.start_run({ jokers = { 'bplus_triboulet_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '10S', '7H', '5C', '3D', '2D' })
    local r = T.play({ '10S' })
    T.eq(r.chips, 5 + 10)
    T.eq(r.mult, 1)
end)

T.test('Triboulet+: vanilla Triboulet forced to "+" gives X2 for a Jack', function()
    T.start_run({ jokers = { 'triboulet' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'JS', '7H', '5C', '3D', '2D' })
    T.eq(T.play({ 'JS' }).mult, 1)
    T.start_run({ jokers = { 'triboulet' }, ante = 3 })
    T.select_blind()
    T.force_behavior('triboulet', 'plus')
    T.set_hand({ 'JS', '7H', '5C', '3D', '2D' })
    T.eq(T.play({ 'JS' }).mult, 1 * 2)
end)
