local T = BPlus.test

T.test('The Nation: play a Flush -> X3 Mult (vanilla: X2 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_tribe_plus' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 * 3)
end)

T.test('The Nation: vanilla joker plays a Flush -> X2 Mult', function()
    T.start_run({ ante = 4, jokers = { 'tribe' } })
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 * 2)
end)

T.test('The Nation: play a Straight Flush (contains a Flush) -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_tribe_plus' } })
    T.select_blind()
    T.set_hand({ '5H', '6H', '7H', '8H', '9H' })
    local r = T.play({ '5H', '6H', '7H', '8H', '9H' })
    T.eq(r.hand, 'Straight Flush')
    T.eq(r.chips, 135)
    T.eq(r.mult, 8 * 3)
end)

T.test('The Nation: play a High Card -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_tribe_plus' } })
    T.select_blind()
    T.set_hand({ 'KS' })
    local r = T.play({ 'KS' })
    T.eq(r.hand, 'High Card')
    T.eq(r.chips, 15)
    T.eq(r.mult, 1)
end)

T.test('The Nation: vanilla joker forced to "+" plays a Flush -> X3 Mult', function()
    T.start_run({ ante = 4, jokers = { 'tribe' } })
    T.force_behavior('tribe', 'plus')
    T.select_blind()
    T.set_hand({ '2H', '5H', '8H', 'JH', 'KH' })
    local r = T.play({ '2H', '5H', '8H', 'JH', 'KH' })
    T.eq(r.hand, 'Flush')
    T.eq(r.chips, 70)
    T.eq(r.mult, 4 * 3)
end)

T.test('The Nation JokerDisplay: shows X3 (Flush) with a Flush selected, X1 without; vanilla forced to "+" shows X3; "+" forced to base shows X2', function()
    T.start_run({ ante = 4, jokers = { 'bplus_tribe_plus', 'tribe' } })
    T.select_blind()
    T.set_hand({ '2H','5H','7H','9H','JH' })
    local d = T.joker_display('bplus_tribe_plus')
    T.eq(d.text, 'X1')
    T.eq(d.reminder, '(Flush)')
    T.highlight({ 1, 2, 3, 4, 5 })
    T.eq(T.joker_display('bplus_tribe_plus').text, 'X3')
    T.eq(T.joker_display('tribe').text, 'X2')
    T.force_behavior('tribe', 'plus')
    T.eq(T.joker_display('tribe').text, 'X3')
    T.force_behavior('bplus_tribe_plus', 'base')
    T.eq(T.joker_display('bplus_tribe_plus').text, 'X2')
end)
