local T = BPlus.test

local function two_pair()
    T.set_hand({ '2S', '2H', '3C', '3D', '7H' })
    return T.play({ '2S', '2H', '3C', '3D' })
end

local function start(joker, hands)
    T.start_run({ jokers = { joker }, hands = hands or 6, ante = 3 })
    T.select_blind()
end

T.test('Three-Piece Suit: play 2 Two Pairs -> +4 + 4 = 8 Mult (vanilla: 2 + 2)', function()
    start('bplus_trousers_plus')
    local r = two_pair()
    T.eq(r.hand, 'Two Pair')
    T.eq(r.mult, 2 + 4)
    T.eq(two_pair().mult, 2 + 4 + 4)
    T.eq(T.joker(1).ability.extra.mult, 4 + 4)
end)

T.test('Three-Piece Suit: play a Full House -> gains +4', function()
    start('bplus_trousers_plus')
    T.set_hand({ '2S', '2H', '2C', '3D', '3H' })
    local r = T.play({ '2S', '2H', '2C', '3D', '3H' })
    T.eq(r.hand, 'Full House')
    T.eq(T.joker(1).ability.extra.mult, 4)
    T.eq(r.mult, 4 + 4)
end)

T.test('Three-Piece Suit: play a Pair -> no gain', function()
    start('bplus_trousers_plus')
    T.set_hand({ '2S', '2H', '5D', '7C', '9S' })
    T.play({ '2S', '2H' })
    T.eq(T.joker(1).ability.extra.mult, 0)
end)

T.test("Three-Piece Suit: Spare Trousers at +6 Mult, upgrade -> keeps +6 Mult, later gains use the '+' rate", function()
    T.start_run({ jokers = { { key = 'trousers', edition = 'holo' } }, hands = 6, ante = 3 })
    T.select_blind()
    two_pair(); two_pair(); two_pair()
    T.eq(T.joker(1).ability.mult, 2 + 2 + 2, 'vanilla value')
    local card = T.upgrade('trousers')
    T.eq(card.ability.extra.mult, 6, 'carried over')
    T.truthy(card.edition and card.edition.holo, 'holo kept')
    local r = two_pair()
    T.eq(card.ability.extra.mult, 6 + 4)
    T.eq(r.mult, 2 + 10 + 10)   -- Two Pair 2 + holo 10 + joker 10
end)

T.test('Three-Piece Suit: Spare Trousers forced to "+" keeps its stored value, only the rate changes', function()
    start('trousers')
    two_pair()
    T.eq(T.joker(1).ability.mult, 2)
    T.force_behavior('trousers', 'plus')
    T.eq(two_pair().mult, 2 + 2 + 4)
    T.eq(T.joker(1).ability.mult, 2 + 4, 'stored on the vanilla card')
    T.force_behavior('trousers', nil)
    T.eq(two_pair().mult, 2 + 6 + 2)
end)

T.test('Three-Piece Suit: forced to base gains +2 and keeps its value', function()
    start('bplus_trousers_plus')
    two_pair()
    T.force_behavior(1, 'base')
    T.eq(two_pair().mult, 2 + 4 + 2)
    T.eq(T.joker(1).ability.extra.mult, 4 + 2)
    T.force_behavior(1, nil)
    T.eq(two_pair().mult, 2 + 6 + 4)
end)

T.test('Three-Piece Suit JokerDisplay: 2 Two Pairs -> +8 ("+") vs +4 (vanilla); stored values kept when forced to "+" / base', function()
    T.start_run({ jokers = { 'bplus_trousers_plus', 'trousers' }, hands = 6, ante = 3 })
    T.select_blind()
    two_pair(); two_pair()
    T.eq(T.joker_display('bplus_trousers_plus').text, '+' .. (4 + 4))
    T.eq(T.joker_display('trousers').text, '+' .. (2 + 2))
    T.force_behavior('trousers', 'plus')
    T.eq(T.joker_display('trousers').text, '+' .. (2 + 2))
    T.force_behavior('bplus_trousers_plus', 'base')
    T.eq(T.joker_display('bplus_trousers_plus').text, '+' .. (4 + 4))
end)
