local T = BPlus.test

T.test('Nomad: play a hand with $6 -> 1 Tarot (vanilla needs $4 or less)', function()
    T.start_run({ ante = 3, dollars = 6, jokers = { 'bplus_vagabond_plus' } })
    T.select_blind()
    T.set_hand({ '2S' })
    T.play({ '2S' })
    T.eq(#G.consumeables.cards, 1)
    T.eq(G.consumeables.cards[1].ability.set, 'Tarot')
end)

T.test('Nomad: play a hand with $7 -> nothing', function()
    T.start_run({ ante = 3, dollars = 7, jokers = { 'bplus_vagabond_plus' } })
    T.select_blind()
    T.set_hand({ '2S' })
    T.play({ '2S' })
    T.eq(#G.consumeables.cards, 0)
end)

T.test('Nomad: slots full -> nothing', function()
    T.start_run({ ante = 3, dollars = 0, consumables = { 'pluto', 'mercury' }, jokers = { 'bplus_vagabond_plus' } })
    T.select_blind()
    T.set_hand({ '2S' })
    T.play({ '2S' })
    T.eq(#G.consumeables.cards, 2)
    T.eq(G.consumeables.cards[1].ability.set, 'Planet')
    T.eq(G.consumeables.cards[2].ability.set, 'Planet')
end)

T.test('Nomad: vanilla Vagabond forced to "+" works with $6', function()
    T.start_run({ ante = 3, dollars = 6, jokers = { 'vagabond' } })
    T.force_behavior('vagabond', 'plus')
    T.select_blind()
    T.set_hand({ '2S' })
    T.play({ '2S' })
    T.eq(#G.consumeables.cards, 1)
end)
