local T = BPlus.test

T.test('Ham Radio: scoring a 10 -> +100 Chips and +4 Mult', function()
    T.start_run({ jokers = { 'bplus_walkie_talkie_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '10S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '10S' })
    T.eq(r.chips, 5 + 10 + 100)
    T.eq(r.mult, 1 + 4)
end)

T.test('Ham Radio: scoring a 4 -> +10 Chips and +40 Mult', function()
    T.start_run({ jokers = { 'bplus_walkie_talkie_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '4S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '4S' })
    T.eq(r.chips, 5 + 4 + 10)
    T.eq(r.mult, 1 + 40)
end)

T.test('Ham Radio: scoring a 7 -> no effect', function()
    T.start_run({ jokers = { 'bplus_walkie_talkie_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '7S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '7S' })
    T.eq(r.chips, 5 + 7)
    T.eq(r.mult, 1)
end)

T.test('Ham Radio: vanilla forced to "+" matches (vanilla 1 + 4, "+" 1 + 4 mult)', function()
    T.start_run({ jokers = { 'walkie_talkie' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '10S', '9C', '6D', '3H', '2S' })
    T.force_behavior('walkie_talkie', 'plus')
    local r = T.play({ '10S' })
    T.eq(r.chips, 5 + 10 + 100)
    T.eq(r.mult, 1 + 4)
end)

T.test('Ham Radio: vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'walkie_talkie' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '10S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '10S' })
    T.eq(r.chips, 5 + 10 + 10)
    T.eq(r.mult, 1 + 4)
end)

T.test('Ham Radio: on a 4, vanilla forced to "+" matches (vanilla 1 + 4, "+" 1 + 40 mult)', function()
    T.start_run({ jokers = { 'walkie_talkie' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '4S', '9C', '6D', '3H', '2S' })
    T.force_behavior('walkie_talkie', 'plus')
    local r = T.play({ '4S' })
    T.eq(r.chips, 5 + 4 + 10)
    T.eq(r.mult, 1 + 40)
end)

T.test('Ham Radio: on a 4, vanilla not forced keeps vanilla numbers', function()
    T.start_run({ jokers = { 'walkie_talkie' }, ante = 3 })
    T.select_blind()
    T.set_hand({ '4S', '9C', '6D', '3H', '2S' })
    local r = T.play({ '4S' })
    T.eq(r.chips, 5 + 4 + 10)
    T.eq(r.mult, 1 + 4)
end)
