local T = BPlus.test

T.test('Tricky Joker: play a Three of a Kind -> +150 Chips (vanilla: +100 Chips)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_wily_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60 + 150)
    T.eq(r.mult, 3)
end)

T.test('Tricky Joker: vanilla joker plays a Three of a Kind -> +100 Chips', function()
    T.start_run({ ante = 4, jokers = { 'wily' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60 + 100)
    T.eq(r.mult, 3)
end)

T.test('Tricky Joker: play a Full House (contains a Three of a Kind) -> +150 Chips', function()
    T.start_run({ ante = 4, jokers = { 'bplus_wily_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78 + 150)
    T.eq(r.mult, 4)
end)

T.test('Tricky Joker: play a Pair -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_wily_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2)
end)

T.test('Tricky Joker: vanilla joker forced to "+" plays a Three of a Kind -> +150 Chips', function()
    T.start_run({ ante = 4, jokers = { 'wily' } })
    T.force_behavior('wily', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60 + 150)
    T.eq(r.mult, 3)
end)

T.test('Tricky Joker JokerDisplay: shows +150 (Three of a Kind) with a Three of a Kind selected, +0 without; vanilla forced to "+" shows +150; "+" forced to base shows +100', function()
    T.start_run({ ante = 4, jokers = { 'bplus_wily_plus', 'wily' } })
    T.select_blind()
    T.set_hand({ 'KS','KH','KC' })
    local d = T.joker_display('bplus_wily_plus')
    T.eq(d.text, '+0')
    T.eq(d.reminder, '(Three of a Kind)')
    T.highlight({ 1, 2, 3 })
    T.eq(T.joker_display('bplus_wily_plus').text, '+150')
    T.eq(T.joker_display('wily').text, '+100')
    T.force_behavior('wily', 'plus')
    T.eq(T.joker_display('wily').text, '+150')
    T.force_behavior('bplus_wily_plus', 'base')
    T.eq(T.joker_display('bplus_wily_plus').text, '+100')
end)
