local T = BPlus.test

T.test('Furious Joker: Pair of Spades -> +5 + 5 Mult (vanilla: +3 + 3)', function()
    T.start_run({ jokers = { 'bplus_wrathful_joker_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KS', '2C', '3C', '5C' })
    local r = T.play({ 1, 2 })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 10 + 10 + 10)
    T.eq(r.mult, 2 + 5 + 5)
end)

T.test('Furious Joker: Pair with no Spades -> +0 Mult', function()
    T.start_run({ jokers = { 'bplus_wrathful_joker_plus' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KC', 'KC', '2C', '3C', '5C' })
    local r = T.play({ 1, 2 })
    T.eq(r.mult, 2)
end)

T.test('Furious Joker: vanilla wrathful_joker gives +3 + 3 Mult', function()
    T.start_run({ jokers = { 'wrathful_joker' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KS', '2C', '3C', '5C' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 3 + 3)
end)

T.test('Furious Joker: vanilla forced to "+" (Carpenter) gives +5 + 5 Mult', function()
    T.start_run({ jokers = { 'wrathful_joker' }, ante = 3 })
    T.select_blind()
    T.force_behavior('wrathful_joker', 'plus')
    T.set_hand({ 'KS', 'KS', '2C', '3C', '5C' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 5 + 5)
end)

T.test('Furious Joker: "+" forced to base gives +3 + 3 Mult', function()
    T.start_run({ jokers = { 'bplus_wrathful_joker_plus' }, ante = 3 })
    T.select_blind()
    T.force_behavior(1, 'base')
    T.set_hand({ 'KS', 'KS', '2C', '3C', '5C' })
    T.eq(T.play({ 1, 2 }).mult, 2 + 3 + 3)
end)

local function highlight(...)
    T.highlight({ ... })
end

T.test('Furious Joker JokerDisplay: "+" shows +10(Spades); vanilla forced to "+" matches; "+" forced to base shows vanilla +6', function()
    T.start_run({ jokers = { 'bplus_wrathful_joker_plus', 'wrathful_joker' }, ante = 3 })
    T.select_blind()
    T.set_hand({ 'KS', 'KS', '2D', '3D', '5D' })
    highlight(1, 2)
    local d = T.joker_display('bplus_wrathful_joker_plus')
    T.eq(d.text, '+10')
    T.eq(d.reminder, '(Spades)')
    local v = T.joker_display('wrathful_joker')
    T.eq(v.text, '+6')
    T.eq(v.reminder, '(Spades)')
    T.force_behavior('wrathful_joker', 'plus')
    v = T.joker_display('wrathful_joker')
    T.eq(v.text, '+10')
    T.eq(v.reminder, '(Spades)')
    T.force_behavior('bplus_wrathful_joker_plus', 'base')
    d = T.joker_display('bplus_wrathful_joker_plus')
    T.eq(d.text, '+6')
    T.eq(d.reminder, '(Spades)')
    T.highlight({})
end)
