local T = BPlus.test

T.test('Goofy Joker: play a Three of a Kind -> +28 Mult (vanilla: +12 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_zany_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 + 28)
end)

T.test('Goofy Joker: vanilla joker plays a Three of a Kind -> +12 Mult', function()
    T.start_run({ ante = 4, jokers = { 'zany' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 + 12)
end)

T.test('Goofy Joker: play a Full House (contains a Three of a Kind) -> +28 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_zany_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78)
    T.eq(r.mult, 4 + 28)
end)

T.test('Goofy Joker: play a Pair -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_zany_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2)
end)

T.test('Goofy Joker: vanilla joker forced to "+" plays a Three of a Kind -> +28 Mult', function()
    T.start_run({ ante = 4, jokers = { 'zany' } })
    T.force_behavior('zany', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 + 28)
end)

T.test('Goofy Joker JokerDisplay: shows +28 (Three of a Kind) with a Three of a Kind selected, +0 without; vanilla forced to "+" shows +28; "+" forced to base shows +12', function()
    T.start_run({ ante = 4, jokers = { 'bplus_zany_plus', 'zany' } })
    T.select_blind()
    T.set_hand({ 'KS','KH','KC' })
    local d = T.joker_display('bplus_zany_plus')
    T.eq(d.text, '+0')
    T.eq(d.reminder, '(Three of a Kind)')
    T.highlight({ 1, 2, 3 })
    T.eq(T.joker_display('bplus_zany_plus').text, '+28')
    T.eq(T.joker_display('zany').text, '+12')
    T.force_behavior('zany', 'plus')
    T.eq(T.joker_display('zany').text, '+28')
    T.force_behavior('bplus_zany_plus', 'base')
    T.eq(T.joker_display('bplus_zany_plus').text, '+12')
end)
