local T = BPlus.test

T.test('Goofy Joker: play a Three of a Kind -> +28 Mult (vanilla: +12 Mult)', function()
    T.start_run({ ante = 4, jokers = { 'bplus_zany_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 + 28)
end)

T.test('Goofy Joker: vanilla joker plays a Three of a Kind -> +12 Mult', function()
    T.start_run({ ante = 4, jokers = { 'zany' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 + 12)
end)

T.test('Goofy Joker: play a Full House (contains a Three of a Kind) -> +28 Mult', function()
    T.start_run({ ante = 4, jokers = { 'bplus_zany_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC', '4D', '4S' })
    local r = T.play({ 'KS', 'KH', 'KC', '4D', '4S' })
    T.eq(r.hand, 'Full House')
    T.eq(r.chips, 78)
    T.eq(r.mult, 4 + 28)
end)

T.test('Goofy Joker: play a Pair -> no effect', function()
    T.start_run({ ante = 4, jokers = { 'bplus_zany_plus' } })
    T.select_blind()
    T.set_hand({ 'KS', 'KH' })
    local r = T.play({ 'KS', 'KH' })
    T.eq(r.hand, 'Pair')
    T.eq(r.chips, 30)
    T.eq(r.mult, 2)
end)

T.test('Goofy Joker: vanilla joker forced to "+" plays a Three of a Kind -> +28 Mult', function()
    T.start_run({ ante = 4, jokers = { 'zany' } })
    T.force_behavior('zany', 'plus')
    T.select_blind()
    T.set_hand({ 'KS', 'KH', 'KC' })
    local r = T.play({ 'KS', 'KH', 'KC' })
    T.eq(r.hand, 'Three of a Kind')
    T.eq(r.chips, 60)
    T.eq(r.mult, 3 + 28)
end)
