#!/usr/bin/env python3
"""Export approved rows of plannig/design/jokers.csv to plannig/specs/jokers/<vanilla_key>.yaml.

Each spec is an implementation ticket. Specs are generated: edit the CSV, then re-run this.
Upgradable rows with status approved, implemented or tested are exported. Blocked rows are
exported too, marked BLOCKED at the top, so they aren't forgotten; BLOCKED.md lists them all.
Values are written as JSON, which is valid YAML, so no YAML library is needed.

Usage: python3 tools/export_specs.py
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "plannig" / "design" / "jokers.csv"
OUT_DIR = ROOT / "plannig" / "specs" / "jokers"
EXPORT_STATUSES = {"approved", "implemented", "tested", "blocked"}

FIELDS = [
    "vanilla_key", "vanilla_name", "vanilla_rarity", "vanilla_cost", "archetype",
    "vanilla_effect", "vanilla_config",
    "pattern", "plus_key", "plus_name", "plus_effect", "plus_config",
    "plus_rarity", "plus_cost", "state_transfer",
    "blueprint_compat", "eternal_compat", "perishable_compat", "carpenter_compat",
    "impl_notes", "acceptance_tests", "status", "art_status",
]
JSON_FIELDS = {"vanilla_config", "plus_config", "state_transfer", "acceptance_tests"}
BOOL_FIELDS = {"blueprint_compat", "eternal_compat", "perishable_compat", "carpenter_compat"}
INT_FIELDS = {"vanilla_cost", "plus_cost"}


def value(field, raw):
    if field in JSON_FIELDS:
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return raw  # e.g. "TBD (Q1)"
    if field in BOOL_FIELDS:
        return raw == "true"
    if field in INT_FIELDS:
        return int(raw)
    return raw


def blocked_on(row):
    """Open questions a blocked row waits on, e.g. ['Q1'], read from its 'TBD (Qn)' markers."""
    found = re.findall(r"TBD \((Q\d+)\)", row["state_transfer"] + " " + row["impl_notes"])
    return sorted(set(found)) or ["unknown: add 'TBD (Qn)' to the row"]


def render(row):
    lines = [
        f"# Implementation ticket for {row['vanilla_key']} -> {row['plus_key']}.",
        "# Generated from plannig/design/jokers.csv by tools/export_specs.py. Edit the CSV, not this file.",
    ]
    if row["status"] == "blocked":
        lines += [
            f"# BLOCKED on {', '.join(blocked_on(row))} (see Open questions in BALATRO_PLUS_AGENT_BRIEF.md).",
            "# The design is written down so it isn't forgotten. Do not implement until it is unblocked.",
        ]
    for field in FIELDS:
        v = value(field, row[field])
        if isinstance(v, list) and v:
            lines.append(f"{field}:")
            lines += [f"  - {json.dumps(item, ensure_ascii=False)}" for item in v]
        else:
            lines.append(f"{field}: {json.dumps(v, ensure_ascii=False)}")
    return "\n".join(lines) + "\n"


def main():
    rows = [r for r in csv.DictReader(CSV_PATH.open())
            if r["status"] in EXPORT_STATUSES and r["upgradable"] == "yes"]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for row in rows:
        (OUT_DIR / f"{row['vanilla_key']}.yaml").write_text(render(row))
    write_blocked_index([r for r in rows if r["status"] == "blocked"])
    print(f"exported {len(rows)} specs to {OUT_DIR.relative_to(ROOT)}")


def write_blocked_index(blocked):
    lines = [
        "# Blocked jokers",
        "",
        "Generated by tools/export_specs.py. These rows are designed but wait on an open question",
        "(see Open questions in BALATRO_PLUS_AGENT_BRIEF.md). Don't implement them yet.",
        "",
        "| Vanilla | \"+\" joker | Planned upgrade | Blocked on |",
        "|---|---|---|---|",
    ]
    lines += [
        f"| {r['vanilla_name']} | {r['plus_name']} | {r['plus_effect']} | {', '.join(blocked_on(r))} |"
        for r in blocked
    ]
    if not blocked:
        lines.append("| (none) | | | |")
    (OUT_DIR / "BLOCKED.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
